INSERT INTO municipality (name, state) VALUES 
('São Paulo', 'SP'),
('Campinas', 'SP'),
('Rio de Janeiro', 'RJ');

-- Administrator
INSERT INTO user_model (name, role, cpf, email, phone, password, street, number, neighborhood, postal_code, municipality_id)
VALUES 
('João Admin', 'ADMINISTRATOR', '00000000000', 'admin@example.com', '(11) 99999-0000', 'hashedpassword', 'Av. Central', '100', 'Centro', '01000-000', 1);

-- Donor
INSERT INTO user_model (name, role, cpf, email, phone, password, street, number, neighborhood, postal_code, municipality_id)
VALUES 
('Maria Doadora', 'DONOR', '11111111111', 'maria@example.com', '(11) 98888-1111', 'hashedpassword', 'Rua das Flores', '200', 'Jardim', '13000-000', 2);

-- Clinic User
INSERT INTO user_model (name, role, cpf, email, phone, password, street, number, neighborhood, postal_code, municipality_id)
VALUES 
('Carlos Clínica', 'CLINIC', '22222222222', 'clinica@example.com', '(21) 97777-2222', 'hashedpassword', 'Rua da Saúde', '300', 'Boa Vista', '20000-000', 3);

INSERT INTO donor (blood_type, eligible, user_id)
VALUES ('O+', TRUE, 2);

INSERT INTO clinic (name, cnpj, street, number, neighborhood, postal_code, municipality_id)
VALUES 
('Clínica Vida', '12345678000199', 'Av. Saúde', '400', 'Centro', '20010-000', 3);

INSERT INTO blood (blood_type, quantity, expiration_date)
VALUES 
('O+', 5.00, CURRENT_DATE + INTERVAL '30 days'),
('A+', 3.50, CURRENT_DATE + INTERVAL '25 days');

INSERT INTO donation_location (name, street, number, neighborhood, postal_code, municipality_id)
VALUES 
('Hemocentro Campinas', 'Rua das Doações', '123', 'Centro', '13000-100', 2);

INSERT INTO blood_stock (blood_type, minimum_stock, maximum_stock, current_stock, donation_location)
VALUES 
('O+', 2.00, 10.00, 5.00, 1),
('A+', 2.00, 10.00, 3.50, 1);

INSERT INTO donation (quantity, collection_date, expiration_date, donor_id, donation_location_id, blood_id)
VALUES 
(0.45, CURRENT_DATE, CURRENT_DATE + INTERVAL '30 days', 1, 1, 1);

INSERT INTO benefit (amount, expiration_date, description, clinic_id, donation_id)
VALUES 
(100.00, CURRENT_DATE + INTERVAL '60 days', 'Desconto em exames', 1, 1);

INSERT INTO notification (message, donor_id)
VALUES 
('Obrigado por sua doação! Seu sangue pode salvar vidas.', 1);

INSERT INTO municipality (name, state) VALUES
('Abadia dos Dourados', 'MG'),
('Abadiânia', 'GO'),
('Abaeté', 'MG'),
('Abaetetuba', 'PA'),
('Abaiara', 'CE'),
('Abaré', 'BA'),
('Abatiá', 'PR'),
('Abdon Batista', 'SC'),
('Abelardo Luz', 'SC'),
('Abel Figueiredo', 'PA'),
('Abre Campo', 'MG'),
('Abreu e Lima', 'PE'),
('Abreulândia', 'TO'),
('Acaiaca', 'MG'),
('Açailândia', 'MA'),
('Acajutiba', 'BA'),
('Acarape', 'CE'),
('Acaraú', 'CE'),
('Acari', 'RN'),
('Acauã', 'PI'),
('Aceguá', 'RS'),
('Acelandia', 'MA'),
('Acopiara', 'CE'),
('Acorizal', 'MT'),
('Acrelândia', 'AC'),
('Adamantina', 'SP'),
('Adelino Garcia', 'PR'),
('Adolfo', 'SP'),
('Adrianópolis', 'PR'),
('Adustina', 'BA'),
('Afogados da Ingazeira', 'PE'),
('Afonso Bezerra', 'RN'),
('Afonso Cláudio', 'ES'),
('Afrânio', 'PE'),
('Afuá', 'PA'),
('Agrestina', 'PE'),
('Agricolândia', 'PI'),
('Agrolândia', 'SC'),
('Agronômica', 'SC'),
('Água Azul do Norte', 'PA'),
('Água Boa', 'MG'),
('Água Boa', 'MT'),
('Água Branca', 'AL'),
('Água Branca', 'PB'),
('Água Branca', 'PI'),
('Água Clara', 'MS'),
('Água Comprida', 'MG'),
('Água Doce', 'SC'),
('Água Doce do Maranhão', 'MA'),
('Água Doce do Norte', 'ES'),
('Água Fria', 'BA'),
('Água Fria de Goiás', 'GO'),
('Aguaí', 'SP'),
('Aguanil', 'MG'),
('Água Nova', 'RN'),
('Água Preta', 'PE'),
('Água Santa', 'RS'),
('Águas Belas', 'PE'),
('Águas de Chapecó', 'SC'),
('Águas de Lindóia', 'SP'),
('Águas de Santa Bárbara', 'SP'),
('Águas de São Pedro', 'SP'),
('Águas Formosas', 'MG'),
('Águas Frias', 'SC'),
('Águas Lindas de Goiás', 'GO'),
('Águas Mornas', 'SC'),
('Águas Vermelhas', 'MG'),
('Agudo', 'RS'),
('Agudos', 'SP'),
('Agudos do Sul', 'PR'),
('Águia Branca', 'ES'),
('Aguiar', 'PB'),
('Aguiarnópolis', 'TO'),
('Aimorés', 'MG'),
('Aiquara', 'BA'),
('Aiuaba', 'CE'),
('Aiuruoca', 'MG'),
('Ajuricaba', 'RS'),
('Alagoa', 'MG'),
('Alagoa Grande', 'PB'),
('Alagoa Nova', 'PB'),
('Alagoinha', 'PB'),
('Alagoinha', 'PE'),
('Alagoinha do Piauí', 'PI'),
('Alagoinhas', 'BA'),
('Alambari', 'SP'),
('Albertina', 'MG'),
('Alcobaça', 'BA'),
('Alcântara', 'MA'),
('Alcantil', 'PB'),
('Alcinópolis', 'MS'),
('Aldeias Altas', 'MA'),
('Alecrim', 'RS'),
('Alegre', 'ES'),
('Alegrete', 'RS'),
('Alegrete do Piauí', 'PI'),
('Alegria', 'RS'),
('Além Paraíba', 'MG'),
('Alenquer', 'PA'),
('Alexania', 'GO'),
('Alfenas', 'MG'),
('Alfredo Chaves', 'ES'),
('Alfredo Vasconcelos', 'MG'),
('Alfredo Wagner', 'SC'),
('Alhandra', 'PB'),
('Aliança', 'PE'),
('Aliança do Tocantins', 'TO'),
('Almadina', 'BA'),
('Almas', 'TO'),
('Almirante Tamandaré', 'PR'),
('Almenara', 'MG'),
('Almino Afonso', 'RN'),
('Alpercata', 'MG'),
('Alpinópolis', 'MG'),
('Alta Floresta', 'MT'),
('Alta Floresta D''Oeste', 'RO'),
('Altamira', 'PA'),
('Altamira do Maranhão', 'MA'),
('Altamira do Paraná', 'PR'),
('Altaneira', 'CE'),
('Alterosa', 'MG'),
('Altinho', 'PE'),
('Altinópolis', 'SP'),
('Alto Alegre', 'RR'),
('Alto Alegre', 'RS'),
('Alto Alegre', 'SP'),
('Alto Alegre do Pindaré', 'MA'),
('Alto Alegre do Maranhão', 'MA'),
('Alto Alegre dos Parecis', 'RO'),
('Alto Araguaia', 'MT'),
('Alto Boa Vista', 'MT'),
('Alto Caparaó', 'MG'),
('Alto Feliz', 'RS'),
('Alto Garças', 'MT'),
('Alto Horizonte', 'GO'),
('Alto Jequitibá', 'MG'),
('Alto Longá', 'PI'),
('Alto Paraguai', 'MT'),
('Alto Paraíso', 'RO'),
('Alto Paraíso', 'PR'),
('Alto Paraíso de Goiás', 'GO'),
('Alto Parnaíba', 'MA'),
('Alto Piquiri', 'PR'),
('Alto Rio Doce', 'MG'),
('Alto Rio Novo', 'ES'),
('Alto Santo', 'CE'),
('Alto Taquari', 'MT'),
('Altônia', 'PR'),
('Alumínio', 'SP'),
('Alvarães', 'AM'),
('Alvarenga', 'MG'),
('Álvares Florence', 'SP'),
('Álvares Machado', 'SP'),
('Álvaro de Carvalho', 'SP'),
('Alvinlândia', 'SP'),
('Alvinópolis', 'MG'),
('Alvorada', 'RS'),
('Alvorada', 'TO'),
('Alvorada de Minas', 'MG'),
('Alvorada D''Oeste', 'RO'),
('Alvorada do Gurguéia', 'PI'),
('Alvorada do Norte', 'GO'),
('Alvorada do Sul', 'PR'),
('Amajari', 'RR'),
('Amambaí', 'MS'),
('Amapá', 'AP'),
('Amapá do Maranhão', 'MA'),
('Amaporã', 'PR'),
('Amaraji', 'PE'),
('Amaral Ferrador', 'RS'),
('Amaralina', 'GO'),
('Amarante', 'PI'),
('Amarante do Maranhão', 'MA'),
('Amargosa', 'BA'),
('Amaturá', 'AM'),
('Amélia Rodrigues', 'BA'),
('Americana', 'SP'),
('Americano do Brasil', 'GO'),
('Américo Brasiliense', 'SP'),
('Américo de Campos', 'SP'),
('Ametista do Sul', 'RS'),
('Amontada', 'CE'),
('Amorinópolis', 'GO'),
('Ampére', 'PR'),
('Anadia', 'AL'),
('Anagé', 'BA'),
('Anahy', 'PR'),
('Anajás', 'PA'),
('Anajatuba', 'MA'),
('Analândia', 'SP'),
('Anamã', 'AM'),
('Ananás', 'TO'),
('Ananindeua', 'PA'),
('Anápolis', 'GO'),
('Anapu', 'PA'),
('Anapurus', 'MA'),
('Anastácio', 'MS'),
('Anaurilândia', 'MS'),
('Andaraí', 'BA'),
('Andirá', 'PR'),
('Andorinha', 'BA'),
('Andradas', 'MG'),
('Andradina', 'SP'),
('André da Rocha', 'RS'),
('Andrelândia', 'MG'),
('Angatuba', 'SP'),
('Angelândia', 'MG'),
('Angélica', 'MS'),
('Angical', 'BA'),
('Angical do Piauí', 'PI'),
('Angicos', 'RN'),
('Angra dos Reis', 'RJ'),
('Anguera', 'BA'),
('Ângulo', 'PR'),
('Anhumas', 'SP'),
('Anicuns', 'GO'),
('Anísio de Abreu', 'PI'),
('Anita Garibaldi', 'SC'),
('Anitápolis', 'SC'),
('Anori', 'AM'),
('Anta Gorda', 'RS'),
('Antas', 'BA'),
('Antonina', 'PR'),
('Antonina do Norte', 'CE'),
('Antônio Almeida', 'PI'),
('Antônio Cardoso', 'BA'),
('Antônio Carlos', 'MG'),
('Antônio Carlos', 'SC'),
('Antônio Dias', 'MG'),
('Antônio João', 'MS'),
('Antônio Martins', 'RN'),
('Antônio Olinto', 'PR'),
('Antônio Prado', 'RS'),
('Antônio Prado de Minas', 'MG'),
('Aparecida', 'PB'),
('Aparecida', 'SP'),
('Aparecida de Goiânia', 'GO'),
('Aparecida do Taboado', 'MS'),
('Aparecida do Rio Doce', 'GO'),
('Aparecida do Rio Negro', 'TO'),
('Aparecida Do Oeste', 'SP'),
('Apiaí', 'SP'),
('Apiacá', 'ES'),
('Apiacás', 'MT'),
('Apicum-Açu', 'MA'),
('Apiúna', 'SC'),
('Apodi', 'RN'),
('Aporá', 'BA'),
('Apuarema', 'BA'),
('Apuiarés', 'CE'),
('Apuí', 'AM'),
('Apucarana', 'PR'),
('Aquidabã', 'SE'),
('Aquidauana', 'MS'),
('Aquiraz', 'CE'),
('Arabutã', 'SC'),
('Araçagi', 'PB'),
('Araçaí', 'MG'),
('Aracaju', 'SE'),
('Araçariguama', 'SP'),
('Araçás', 'BA'),
('Aracati', 'CE'),
('Aracatu', 'BA'),
('Araçatuba', 'SP'),
('Aracê', 'ES'),
('Araçoiaba', 'PE'),
('Araçoiaba da Serra', 'SP'),
('Aracruz', 'ES'),
('Araçu', 'GO'),
('Araçuaí', 'MG'),
('Aragarças', 'GO'),
('Aragoiânia', 'GO'),
('Aragona', 'TO'),
('Araguacema', 'TO'),
('Araguaiana', 'MT'),
('Araguainha', 'MT'),
('Araguana', 'MA'),
('Araguari', 'MG'),
('Araguatins', 'TO'),
('Araioses', 'MA'),
('Aral Moreira', 'MS'),
('Arambaré', 'RS'),
('Arame', 'MA'),
('Aramina', 'SP'),
('Arandu', 'SP'),
('Arantina', 'MG'),
('Araranguá', 'SC'),
('Araraquara', 'SP'),
('Araras', 'SP'),
('Ararendá', 'CE'),
('Arari', 'MA'),
('Araricá', 'RS'),
('Araripina', 'PE'),
('Araruama', 'RJ'),
('Araruna', 'PB'),
('Araruna', 'PR'),
('Aratiba', 'RS'),
('Aratuba', 'CE'),
('Aratuípe', 'BA'),
('Araxá', 'MG'),
('Arceburgo', 'MG'),
('Arco-Íris', 'SP'),
('Arcos', 'MG'),
('Arcoverde', 'PE'),
('Areado', 'MG'),
('Areal', 'RJ'),
('Arealva', 'SP'),
('Areia', 'PB'),
('Areia Branca', 'RN'),
('Areia de Baraúnas', 'PB'),
('Areial', 'PB'),
('Areias', 'SP'),
('Areiópolis', 'SP'),
('Arenápolis', 'MT'),
('Arenópolis', 'GO'),
('Arez', 'RN'),
('Argirita', 'MG'),
('Aricanduva', 'MG'),
('Arinos', 'MG'),
('Aripuanã', 'MT'),
('Ariranha', 'SP'),
('Ariranha do Ivaí', 'PR'),
('Armação dos Búzios', 'RJ'),
('Armazém', 'SC'),
('Arneiroz', 'CE'),
('Aroazes', 'PI'),
('Aroeiras', 'PB'),
('Aroeiras do Itaim', 'PI'),
('Arroio do Meio', 'RS'),
('Arroio do Sal', 'RS'),
('Arroio do Tigre', 'RS'),
('Arroio dos Ratos', 'RS'),
('Arroio Grande', 'RS'),
('Arroio Trinta', 'SC'),
('Artur Nogueira', 'SP'),
('Aruanã', 'GO'),
('Arujá', 'SP'),
('Arvoredo', 'SC'),
('Arvorezinha', 'RS'),
('Asa Branca', 'PR'),
('Ascurra', 'SC'),
('Assaí', 'PR'),
('Assaré', 'CE'),
('Assis', 'SP'),
('Assis Brasil', 'AC'),
('Assis Chateaubriand', 'PR'),
('Assunção', 'PB'),
('Assunção do Piauí', 'PI'),
('Astolfo Dutra', 'MG'),
('Astorga', 'PR'),
('Atalaia', 'AL'),
('Atalaia', 'PR'),
('Ataleia', 'MG'),
('Atalanta', 'SC'),
('Atibaia', 'SP'),
('Atílio Vivácqua', 'ES'),
('Augustinópolis', 'TO'),
('Augusto Corrêa', 'PA'),
('Augusto de Lima', 'MG'),
('Augusto Pestana', 'RS'),
('Augusto Severo', 'RN'),
('Áurea', 'RS'),
('Aurelino Leal', 'BA'),
('Auriflama', 'SP'),
('Aurilândia', 'GO'),
('Aurora', 'CE'),
('Aurora', 'SC'),
('Aurora do Pará', 'PA'),
('Aurora do Tocantins', 'TO'),
('Autazes', 'AM'),
('Avaí', 'SP'),
('Avanhandava', 'SP'),
('Avaré', 'SP'),
('Aveiro', 'PA'),
('Avelino Lopes', 'PI'),
('Avelinópolis', 'GO'),
('Axixá', 'MA'),
('Axixá do Tocantins', 'TO'),
('Babaçulândia', 'TO'),
('Bacabal', 'MA'),
('Bacabeira', 'MA'),
('Bacuri', 'MA'),
('Bacurituba', 'MA'),
('Bady Bassitt', 'SP'),
('Baependi', 'MG'),
('Bagé', 'RS'),
('Bagre', 'PA'),
('Baía da Traição', 'PB'),
('Baía Formosa', 'RN'),
('Baianópolis', 'BA'),
('Baião', 'PA'),
('Baixa Grande', 'BA'),
('Baixa Grande do Ribeiro', 'PI'),
('Balbinos', 'SP'),
('Baldim', 'MG'),
('Baliza', 'GO'),
('Balneário Arroio do Silva', 'SC'),
('Balneário Barra do Sul', 'SC'),
('Balneário Camboriú', 'SC'),
('Balneário Gaivota', 'SC'),
('Balneário Piçarras', 'SC'),
('Balneário Rincão', 'SC'),
('Banabuiú', 'CE'),
('Bananal', 'SP'),
('Bandeira', 'MG'),
('Bandeira do Sul', 'MG'),
('Bandeirante', 'SC'),
('Bandeirantes', 'MS'),
('Bandeirantes', 'PR'),
('Barão', 'RS'),
('Barão de Cocais', 'MG'),
('Barão de Grajaú', 'MA'),
('Barão de Melgaço', 'MT'),
('Barão de Monte Alto', 'MG'),
('Barão do Triunfo', 'RS'),
('Barbalha', 'CE'),
('Barbosa', 'SP'),
('Barbosa Ferraz', 'PR'),
('Barcarena', 'PA'),
('Barcelona', 'RN'),
('Barcelos', 'AM'),
('Barra', 'BA'),
('Barra Bonita', 'SP'),
('Barra Bonita', 'SC'),
('Barra de Guabiraba', 'PE'),
('Barra de Santa Rosa', 'PB'),
('Barra de Santana', 'PB'),
('Barra de São Francisco', 'ES'),
('Barra de São Miguel', 'AL'),
('Barra de São Miguel', 'PB'),
('Barra do Bugres', 'MT'),
('Barra do Chapéu', 'SP'),
('Barra do Corda', 'MA'),
('Barra do Garças', 'MT'),
('Barra do Jacaré', 'PR'),
('Barra do Mendes', 'BA'),
('Barra do Ouro', 'TO'),
('Barra do Piraí', 'RJ'),
('Barra do Quaraí', 'RS'),
('Barra do Ribeiro', 'RS'),
('Barra do Rio Azul', 'RS'),
('Barra do Rocha', 'BA'),
('Barra do Turvo', 'SP'),
('Barra D''Alcântara', 'PI'),
('Barra Funda', 'RS'),
('Barra Mansa', 'RJ'),
('Barra Velha', 'SC'),
('Barracão', 'PR'),
('Barracão', 'RS'),
('Barras', 'PI'),
('Barreiras', 'BA'),
('Barreirinhas', 'MA'),
('Barreiros', 'PE'),
('Barretos', 'SP'),
('Barrinha', 'SP'),
('Barro', 'CE'),
('Barro Alto', 'BA'),
('Barro Alto', 'GO'),
('Barro Duro', 'PI'),
('Barrocas', 'BA'),
('Barrolândia', 'TO'),
('Barroquinha', 'CE'),
('Barros Cassal', 'RS'),
('Barroso', 'MG'),
('Barueri', 'SP'),
('Basturi', 'SP'),
('Batatais', 'SP'),
('Batayporã', 'MS'),
('Batalha', 'AL'),
('Batalha', 'PI'),
('Bauru', 'SP'),
('Bayeux', 'PB'),
('Bebedouro', 'SP'),
('Beberibe', 'CE'),
('Bela Cruz', 'CE'),
('Bela Vista', 'MS'),
('Bela Vista de Goiás', 'GO'),
('Bela Vista de Minas', 'MG'),
('Bela Vista do Caroba', 'PR'),
('Bela Vista do Maranhão', 'MA'),
('Bela Vista do Piauí', 'PI'),
('Bela Vista do Toldo', 'SC'),
('Belém', 'AL'),
('Belém', 'PA'),
('Belém', 'PB'),
('Belém de Maria', 'PE'),
('Belém do Brejo do Cruz', 'PB'),
('Belém do Piauí', 'PI'),
('Belém do São Francisco', 'PE'),
('Belford Roxo', 'RJ'),
('Belmiro Braga', 'MG'),
('Belmonte', 'BA'),
('Belmonte', 'SC'),
('Belo Campo', 'BA'),
('Belo Horizonte', 'MG'),
('Belo Jardim', 'PE'),
('Belo Monte', 'AL'),
('Belo Oriente', 'MG'),
('Belo Vale', 'MG'),
('Beneditinos', 'PI'),
('Benedito Leite', 'MA'),
('Benedito Novo', 'SC'),
('Benevides', 'PA'),
('Benjamin Constant', 'AM'),
('Benjamin Constant do Sul', 'RS'),
('Bento de Abreu', 'SP'),
('Bento Fernandes', 'RN'),
('Bento Gonçalves', 'RS'),
('Bequimão', 'MA'),
('Berilo', 'MG'),
('Berizal', 'MG'),
('Bernardino Batista', 'PB'),
('Bernardino de Campos', 'SP'),
('Bernardo de Irigoyen', 'SC'),
('Bernardo do Mearim', 'MA'),
('Beruri', 'AM'),
('Betim', 'MG'),
('Bezerros', 'PE'),
('Bias Fortes', 'MG'),
('Bicas', 'MG'),
('Biguaçu', 'SC'),
('Bilac', 'SP'),
('Biritiba Mirim', 'SP'),
('Birigui', 'SP'),
('Biscoitos', 'RJ'),
('Bismarck', 'RN'),
('Bituruna', 'PR'),
('Boa Esperança', 'MG'),
('Boa Esperança', 'PR'),
('Boa Esperança do Iguaçu', 'PR'),
('Boa Esperança do Sul', 'SP'),
('Boa Hora', 'PI'),
('Boa Nova', 'BA'),
('Boa Ventura', 'PB'),
('Boa Ventura de São Roque', 'PR'),
('Boa Viagem', 'CE'),
('Boa Vista', 'PB'),
('Boa Vista', 'RR'),
('Boa Vista das Missões', 'RS'),
('Boa Vista do Buricá', 'RS'),
('Boa Vista do Cadeado', 'RS'),
('Boa Vista do Gurupi', 'MA'),
('Boa Vista do Incra', 'RS'),
('Boa Vista do Ramos', 'AM'),
('Boa Vista do Sul', 'RS'),
('Boa Vista do Tupim', 'BA'),
('Boca da Mata', 'AL'),
('Boca do Acre', 'AM'),
('Bocaina', 'PI'),
('Bocaina', 'SP'),
('Bocaina de Minas', 'MG'),
('Bocaina do Sul', 'SC'),
('Botucatu', 'SP'),
('Botumirim', 'MG'),
('Boqueirão', 'PB'),
('Boqueirão do Leão', 'RS'),
('Boqueirão do Piauí', 'PI'),
('Borá', 'SP'),
('Borba', 'AM'),
('Borbae', 'CE'),
('Borrazópolis', 'PR'),
('Borreiros', 'PE'),
('Bortolan', 'RS'),
('Borda da Mata', 'MG'),
('Botelhos', 'MG'),
('Bragança', 'PA'),
('Bragança Paulista', 'SP'),
('Branquinha', 'AL'),
('Brasilândia', 'MS'),
('Brasilândia do Tocantins', 'TO'),
('Brasilândia do Sul', 'PR'),
('Brasil Novo', 'PA'),
('Brasileia', 'AC'),
('Brasileira', 'PI'),
('Brasília', 'DF'),
('Brás Pires', 'MG'),
('Braúnas', 'MG'),
('Braúna', 'SP'),
('Braço do Norte', 'SC'),
('Braço do Trombudo', 'SC'),
('Brejinho', 'PE'),
('Brejinho', 'RN'),
('Brejinho de Nazaré', 'TO'),
('Brejo', 'MA'),
('Brejo Alegre', 'SP'),
('Brejo da Madre de Deus', 'PE'),
('Brejo de Areia', 'MA'),
('Brejo do Cruz', 'PB'),
('Brejo do Piauí', 'PI'),
('Brejo dos Santos', 'PB'),
('Brejo Grande', 'SE'),
('Brejo Grande do Araguaia', 'PA'),
('Brejo Santo', 'CE'),
('Brejões', 'BA'),
('Brejolândia', 'BA'),
('Breu Branco', 'PA'),
('Breves', 'PA'),
('Britânia', 'GO'),
('Brodowski', 'SP'),
('Brochier', 'RS'),
('Brumadinho', 'MG'),
('Brumado', 'BA'),
('Brunópolis', 'SC'),
('Bueno Brandão', 'MG'),
('Buenópolis', 'MG'),
('Buenos Aires', 'PE'),
('Buerarema', 'BA'),
('Bugre', 'PA'),
('Bujari', 'AC'),
('Buri', 'SP'),
('Buritama', 'SP'),
('Buriti', 'MA'),
('Buriti Alegre', 'GO'),
('Buriti Bravo', 'MA'),
('Buriticupu', 'MA'),
('Buritinópolis', 'GO'),
('Buritirama', 'BA'),
('Buritirana', 'MA'),
('Buritis', 'MG'),
('Buritis', 'RO'),
('Buritizal', 'SP'),
('Cabaceiras', 'PB'),
('Cabaceiras do Paraguaçu', 'BA'),
('Cabeceira Grande', 'MG'),
('Cabeceiras', 'GO'),
('Cabeceiras do Piauí', 'PI'),
('Cabedelo', 'PB'),
('Cabo de Santo Agostinho', 'PE'),
('Cabo Frio', 'RJ'),
('Caboré', 'MA'),
('Cabrobó', 'PE'),
('Caçapava', 'SP'),
('Caçapava do Sul', 'RS'),
('Caçador', 'SC'),
('Caçador de Toledo', 'PR'),
('Caém', 'BA'),
('Caetanos', 'BA'),
('Caeté', 'MG'),
('Caetés', 'PE'),
('Caetité', 'BA'),
('Cafezal do Sul', 'PR'),
('Cafeara', 'PR'),
('Cafelândia', 'PR'),
('Cafelândia', 'SP'),
('Caiabu', 'SP'),
('Caiana', 'MG'),
('Caiapônia', 'GO'),
('Caicó', 'RN'),
('Caieiras', 'SP'),
('Cairu', 'BA'),
('Caiuá', 'SP'),
('Cajamar', 'SP'),
('Cajapió', 'MA'),
('Cajari', 'MA'),
('Cajati', 'SP'),
('Cajazeiras', 'PB'),
('Cajazeiras do Piauí', 'PI'),
('Cajobi', 'SP'),
('Cajueiro', 'AL'),
('Cajuri', 'MG'),
('Cajuru', 'SP'),
('Calçado', 'PE'),
('Caldas', 'MG'),
('Caldas Brandão', 'PB'),
('Caldas Novas', 'GO'),
('Caldazinha', 'GO'),
('Caldeirão Grande', 'BA'),
('Caldeirão Grande do Piauí', 'PI'),
('Califórnia', 'PR'),
('Calmon', 'SC'),
('Calumbi', 'PE'),
('Camacan', 'BA'),
('Camacho', 'MG'),
('Camalaú', 'PB'),
('Camamu', 'BA'),
('Cambará', 'PR'),
('Cambará do Sul', 'RS'),
('Cambé', 'PR'),
('Cambira', 'PR'),
('Camboriú', 'SC'),
('Cambuci', 'RJ'),
('Cambuí', 'MG'),
('Cambuquira', 'MG'),
('Cametá', 'PA'),
('Campanha', 'MG'),
('Campanário', 'MG'),
('Campestre', 'AL'),
('Campestre', 'MG'),
('Campestre da Serra', 'RS'),
('Campestre de Goiás', 'GO'),
('Campina da Lagoa', 'PR'),
('Campina das Missões', 'RS'),
('Campina do Monte Alegre', 'SP'),
('Campina do Simão', 'PR'),
('Campina Grande', 'PB'),
('Campina Grande do Sul', 'PR'),
('Campina Verde', 'MG'),
('Campinápolis', 'MT'),
('Campinas', 'SP'),
('Campinas do Piauí', 'PI'),
('Campinas do Sul', 'RS'),
('Campinaçu', 'GO'),
('Campinorte', 'GO'),
('Campo Alegre', 'AL'),
('Campo Alegre', 'SC'),
('Campo Alegre de Goiás', 'GO'),
('Campo Alegre de Lourdes', 'BA'),
('Campo Alegre do Fidalgo', 'PI'),
('Campo Azul', 'MG'),
('Campo Belo', 'MG'),
('Campo Belo do Sul', 'SC'),
('Campo Bom', 'RS'),
('Campo Bonito', 'PR'),
('Campo do Brito', 'SE'),
('Campo do Meio', 'MG'),
('Campo do Tenente', 'PR'),
('Campo Erê', 'SC'),
('Campo Florido', 'MG'),
('Campo Formoso', 'BA'),
('Campo Grande', 'AL'),
('Campo Grande', 'MS'),
('Campo Grande', 'RN'),
('Campo Grande do Piauí', 'PI'),
('Campo Largo', 'PR'),
('Campo Largo do Piauí', 'PI'),
('Campo Limpo de Goiás', 'GO'),
('Campo Limpo Paulista', 'SP'),
('Campo Magro', 'PR'),
('Campo Maior', 'PI'),
('Campo Mourão', 'PR'),
('Campo Novo', 'RS'),
('Campo Novo de Rondônia', 'RO'),
('Campo Novo do Parecis', 'MT'),
('Campo Redondo', 'RN'),
('Campos Altos', 'MG'),
('Campos Belos', 'GO'),
('Campos de Júlio', 'MT'),
('Campos do Jordão', 'SP'),
('Campos dos Goytacazes', 'RJ'),
('Campos Gerais', 'MG'),
('Campos Lindos', 'TO'),
('Campos Novos', 'SC'),
('Campos Novos Paulista', 'SP'),
('Campos Sales', 'CE'),
('Campos Verdes', 'GO'),
('Canabrava do Norte', 'MT'),
('Cananéia', 'SP'),
('Canapi', 'AL'),
('Canápolis', 'MG'),
('Canarana', 'BA'),
('Canarana', 'MT'),
('Canas', 'SP'),
('Canavieira', 'PI'),
('Canavieiras', 'BA'),
('Candeal', 'BA'),
('Candeias', 'BA'),
('Candeias', 'MG'),
('Candelária', 'RS'),
('Candiota', 'RS'),
('Candói', 'PR'),
('Canelinha', 'SC'),
('Canguaretama', 'RN'),
('Canguçu', 'RS'),
('Canindé', 'CE'),
('Canindé de São Francisco', 'SE'),
('Canitar', 'SP'),
('Canoinhas', 'SC'),
('Cansanção', 'BA'),
('Cantagalo', 'MG'),
('Cantagalo', 'PR'),
('Cantagalo', 'RJ'),
('Canto do Buriti', 'PI'),
('Canudos', 'BA'),
('Canudos do Vale', 'RS'),
('Capão Alto', 'SC'),
('Capão Bonito', 'SP'),
('Capão Bonito do Sul', 'RS'),
('Capão da Canoa', 'RS'),
('Capão do Cipó', 'RS'),
('Capão do Leão', 'RS'),
('Caparaó', 'MG'),
('Capela', 'AL'),
('Capela', 'SE'),
('Capela de Santana', 'RS'),
('Capela do Alto', 'SP'),
('Capela Nova', 'MG'),
('Capelinha', 'MG'),
('Capim', 'PB'),
('Capim Branco', 'MG'),
('Capinópolis', 'MG'),
('Capinzal', 'SC'),
('Capinzal do Norte', 'MA'),
('Capistrano', 'CE'),
('Capitão', 'RS'),
('Capitão Andrade', 'MG'),
('Capitão de Campos', 'PI'),
('Capitão Enéas', 'MG'),
('Capitão Leônidas Marques', 'PR'),
('Capitão Poço', 'PA'),
('Capivari', 'SP'),
('Capivari de Baixo', 'SC'),
('Capivarí do Sul', 'RS'),
('Capoeiras', 'PE'),
('Caputira', 'MG'),
('Caraá', 'RS'),
('Caracaraí', 'RR'),
('Caracol', 'MS'),
('Caracol', 'PI'),
('Caraguatatuba', 'SP'),
('Caraí', 'MG'),
('Caraíbas', 'BA'),
('Carapebus', 'RJ'),
('Carapicuíba', 'SP'),
('Caratinga', 'MG'),
('Carauari', 'AM'),
('Caraúbas', 'PB'),
('Caraúbas', 'RN'),
('Caraúbas do Piauí', 'PI'),
('Caravelas', 'BA'),
('Carazinho', 'RS'),
('Carbonita', 'MG'),
('Cardeal da Silva', 'BA'),
('Cardoso', 'SP'),
('Cardoso Moreira', 'RJ'),
('Careiro', 'AM'),
('Careiro da Várzea', 'AM'),
('Cariacica', 'ES'),
('Carinhanha', 'BA'),
('Carira', 'SE'),
('Cariré', 'CE'),
('Caririaçu', 'CE'),
('Cariús', 'CE'),
('Carlinda', 'MT'),
('Carlos Barbosa', 'RS'),
('Carlos Chagas', 'MG'),
('Carlos Gomes', 'RS'),
('Carmésia', 'MG'),
('Carmo', 'RJ'),
('Carmo da Cachoeira', 'MG'),
('Carmo da Mata', 'MG'),
('Carmo de Minas', 'MG'),
('Carmo do Cajuru', 'MG'),
('Carmo do Paranaíba', 'MG'),
('Carmo do Rio Claro', 'MG'),
('Carmópolis', 'SE'),
('Carmópolis de Minas', 'MG'),
('Carnaíba', 'PE'),
('Carnaúba dos Dantas', 'RN'),
('Carnaubais', 'RN'),
('Carnaubal', 'CE'),
('Carneirinho', 'MG'),
('Carneiros', 'AL'),
('Caroebe', 'RR'),
('Carolina', 'MA'),
('Carpina', 'PE'),
('Carrancas', 'MG'),
('Carrapateira', 'PB'),
('Carrasco Bonito', 'TO'),
('Caruaru', 'PE'),
('Carutapera', 'MA'),
('Casca', 'RS'),
('Cascalho Rico', 'MG'),
('Cascavel', 'CE'),
('Cascavel', 'PR'),
('Caseara', 'TO'),
('Caseiros', 'RS'),
('Casimiro de Abreu', 'RJ'),
('Casinhas', 'PE'),
('Casserengue', 'PB'),
('Cassia', 'MG'),
('Cássia dos Coqueiros', 'SP'),
('Castanhal', 'PA'),
('Castanheira', 'MT'),
('Castanheiras', 'RO'),
('Castelo', 'ES'),
('Castelo do Piauí', 'PI'),
('Castilho', 'SP'),
('Castro', 'PR'),
('Castro Alves', 'BA'),
('Cataguases', 'MG'),
('Catalão', 'GO'),
('Catanduva', 'SP'),
('Catas Altas', 'MG'),
('Catas Altas da Noruega', 'MG'),
('Catende', 'PE'),
('Catiguá', 'SP'),
('Catingueira', 'PB'),
('Catolândia', 'BA'),
('Catolé do Rocha', 'PB'),
('Catu', 'BA'),
('Catuji', 'MG'),
('Catunda', 'CE'),
('Caturaí', 'GO'),
('Caturité', 'PB'),
('Cavalcante', 'GO'),
('Caxambu', 'MG'),
('Caxambu do Sul', 'SC'),
('Caxias', 'MA'),
('Caxias do Sul', 'RS'),
('Ceilândia', 'DF'),
('Ceará-Mirim', 'RN'),
('Cedral', 'MA'),
('Cedral', 'SP'),
('Cedro', 'CE'),
('Cedro de São João', 'SE'),
('Celso Ramos', 'SC'),
('Centenário', 'RS'),
('Centenário', 'TO'),
('Centenário do Sul', 'PR'),
('Central', 'BA'),
('Central de Minas', 'MG'),
('Central do Maranhão', 'MA'),
('Centralina', 'MG'),
('Centro do Guilherme', 'MA'),
('Centro Novo do Maranhão', 'MA'),
('Cerejeiras', 'RO'),
('Cerro Azul', 'PR'),
('Cerro Branco', 'RS'),
('Cerro Corá', 'RN'),
('Cerro Grande', 'RS'),
('Cerro Grande do Sul', 'RS'),
('Cerro Largo', 'RS'),
('Cerro Negro', 'SC'),
('Cesário Lange', 'SP'),
('Chã de Alegria', 'PE'),
('Chã Grande', 'PE'),
('Chã Preta', 'AL'),
('Chaval', 'CE'),
('Chavantes', 'SP'),
('Chaves', 'PA'),
('Chiador', 'MG'),
('Chopinzinho', 'PR'),
('Choró', 'CE'),
('Chorozinho', 'CE'),
('Chuí', 'RS'),
('Chupinguaia', 'RO'),
('Chuvisca', 'RS'),
('Cianorte', 'PR'),
('Cibatã', 'SP'),
('Cidade Gaúcha', 'PR'),
('Cidade Ocidental', 'GO'),
('Cidelândia', 'MA'),
('Cidreira', 'RS'),
('Cifar', 'PB'),
('Cipó', 'BA'),
('Cipotânea', 'MG'),
('Ciríaco', 'RS'),
('Claraval', 'MG'),
('Claro dos Poções', 'MG'),
('Cláudia', 'MT'),
('Claudio', 'MG'),
('Clementina', 'SP'),
('Coaraci', 'BA'),
('Coari', 'AM'),
('Cocal', 'PI'),
('Cocal de Telha', 'PI'),
('Cocal dos Alves', 'PI'),
('Cococi', 'CE'),
('Cocuraí', 'PE'),
('Codajás', 'AM'),
('Codó', 'MA'),
('Coelho Neto', 'MA'),
('Coimbra', 'MG'),
('Coité do Noia', 'AL'),
('Colares', 'PA'),
('Colatina', 'ES'),
('Colinas', 'MA'),
('Colinas', 'RS'),
('Colinas do Sul', 'GO'),
('Colinas do Tocantins', 'TO'),
('Colméia', 'TO'),
('Colorado', 'PR'),
('Colorado', 'RS'),
('Colorado do Oeste', 'RO'),
('Coluna', 'MG'),
('Conceição', 'PB'),
('Conceição da Aparecida', 'MG'),
('Conceição da Barra', 'ES'),
('Conceição da Boa Vista', 'ES'),
('Conceição da Feira', 'BA'),
('Conceição das Alagoas', 'MG'),
('Conceição das Pedras', 'MG'),
('Conceição de Ipanema', 'MG'),
('Conceição do Almeida', 'BA'),
('Conceição do Araguaia', 'PA'),
('Conceição do Canindé', 'PI'),
('Conceição do Castelo', 'ES'),
('Conceição do Coité', 'BA'),
('Conceição do Jacuípe', 'BA'),
('Conceição do Lago Açu', 'MA'),
('Conceição do Mato Dentro', 'MG'),
('Conceição do Pará', 'MG'),
('Conceição do Rio Verde', 'MG'),
('Conceição do Tocantins', 'TO'),
('Conceição dos Ouros', 'MG'),
('Conchal', 'SP'),
('Conchas', 'SP'),
('Condado', 'PB'),
('Condado', 'PE'),
('Conde', 'BA'),
('Conde', 'PB'),
('Condeúba', 'BA'),
('Condor', 'RS'),
('Cônego Marinho', 'MG'),
('Confins', 'MG'),
('Conflência', 'MT'),
('Conquista', 'MG'),
('Conquista D''Oeste', 'MT'),
('Conselheiro Lafaiete', 'MG'),
('Conselheiro Pena', 'MG'),
('Consolação', 'MG'),
('Constantina', 'RS'),
('Contagem', 'MG'),
('Contenda', 'PR'),
('Coqueiral', 'MG'),
('Coqueiro Baixo', 'RS'),
('Coqueiro Seco', 'AL'),
('Coqueiros do Sul', 'RS'),
('Coração de Jesus', 'MG'),
('Coração de Maria', 'BA'),
('Cordeiro', 'RJ'),
('Cordeirópolis', 'SP'),
('Cordilheira Alta', 'SC'),
('Cordisburgo', 'MG'),
('Cordislândia', 'MG'),
('Coribe', 'BA'),
('Corino', 'RN'),
('Coroados', 'SP'),
('Coroaci', 'MG'),
('Coronel Barros', 'RS'),
('Coronel Ezequiel', 'RN'),
('Coronel Fabriciano', 'MG'),
('Coronel Freitas', 'SC'),
('Coronel João Pessoa', 'RN'),
('Coronel José Dias', 'PI'),
('Coronel Macedo', 'SP'),
('Coronel Martins', 'SC'),
('Coronel Murta', 'MG'),
('Coronel Pacheco', 'MG'),
('Coronel Pilar', 'RS'),
('Coronel Vivida', 'PR'),
('Coronel Xavier Chaves', 'MG'),
('Coronelândia', 'MA'),
('Corumbá', 'MS'),
('Corumbá de Goiás', 'GO'),
('Corumbal', 'MG'),
('Corumbiara', 'RO'),
('Corupá', 'SC'),
('Coruripe', 'AL'),
('Cosmópolis', 'SP'),
('Cosmorama', 'SP'),
('Costa Marques', 'RO'),
('Cotegipe', 'BA'),
('Cotia', 'SP'),
('Cotiporã', 'RS'),
('Cotriguaçu', 'MT'),
('Cristais', 'MG'),
('Cristal', 'RS'),
('Cristal do Sul', 'RS'),
('Cristalândia', 'TO'),
('Cristalândia do Piauí', 'PI'),
('Cristianópolis', 'GO'),
('Cristiano Otoni', 'MG'),
('Cristina', 'MG'),
('Cristinápolis', 'SE'),
('Cristino Castro', 'PI'),
('Cristópolis', 'BA'),
('Crixás', 'GO'),
('Crixás do Tocantins', 'TO'),
('Crucilândia', 'MG'),
('Cruz', 'CE'),
('Cruz Alta', 'RS'),
('Cruzália', 'SP'),
('Cruz das Almas', 'BA'),
('Cruz do Espírito Santo', 'PB'),
('Cruzaltense', 'RS'),
('Cruzeiro', 'SP'),
('Cruzeiro da Fortaleza', 'MG'),
('Cruzeiro do Iguaçu', 'PR'),
('Cruzeiro do Oeste', 'PR'),
('Cruzeiro do Sul', 'AC'),
('Cruzeiro do Sul', 'PR'),
('Cruzeiro do Sul', 'RS'),
('Cruzeta', 'RN'),
('Cruzília', 'MG'),
('Cubati', 'PB'),
('Cunha', 'SP'),
('Cunha Porã', 'SC'),
('Cunhataí', 'SC'),
('Cupira', 'PE'),
('Curaçá', 'BA'),
('Curimatá', 'PI'),
('Curionópolis', 'PA'),
('Curitiba', 'PR'),
('Curitibanos', 'SC'),
('Currais', 'PI'),
('Currais Novos', 'RN'),
('Curral de Cima', 'PB'),
('Curral Novo do Piauí', 'PI'),
('Curral Velho', 'PB'),
('Curralinho', 'PA'),
('Curvelo', 'MG'),
('Custódia', 'PE'),
('Cutias', 'AP'),
('Damiana', 'PI'),
('Damião', 'PB'),
('Damianópolis', 'GO'),
('Damolândia', 'GO'),
('Daniel de Carvalho', 'MG'),
('Dário Meira', 'BA'),
('Davinópolis', 'GO'),
('Davinópolis', 'MA'),
('Delegado de Almeida', 'MG'),
('Delfim Moreira', 'MG'),
('Delfinópolis', 'MG'),
('Delmiro Gouveia', 'AL'),
('Delta', 'MG'),
('Demerval Lobão', 'PI'),
('Denise', 'MT'),
('Derrubadas', 'RS'),
('Dezesseis de Novembro', 'RS'),
('Diadema', 'SP'),
('Diamante', 'PB'),
('Diamante do Norte', 'PR'),
('Diamante do Sul', 'PR'),
('Diamante D''Oeste', 'PR'),
('Diamantina', 'MG'),
('Diamantino', 'MT'),
('Dianópolis', 'TO'),
('Didática', 'MG'),
('Divina Pastora', 'SE'),
('Divinésia', 'MG'),
('Divino', 'MG'),
('Divino das Laranjeiras', 'MG'),
('Divino de São Lourenço', 'ES'),
('Divinolândia', 'SP'),
('Divinolândia de Minas', 'MG'),
('Divinópolis', 'MG'),
('Divinópolis de Goiás', 'GO'),
('Divisa Alegre', 'MG'),
('Divisa Nova', 'MG'),
('Divisópolis', 'MG'),
('Dois Irmãos', 'RS'),
('Dois Irmãos das Missões', 'RS'),
('Dois Irmãos do Buriti', 'MS'),
('Dois Lajeados', 'RS'),
('Dois Riachos', 'AL'),
('Dois Vizinhos', 'PR'),
('Dona Emma', 'SC'),
('Dona Francisca', 'RS'),
('Dona Inês', 'PB'),
('Dores de Campos', 'MG'),
('Dores de Guanhães', 'MG'),
('Dores do Indaiá', 'MG'),
('Dores do Rio Preto', 'ES'),
('Doresópolis', 'MG'),
('Douradina', 'MS'),
('Douradina', 'PR'),
('Dourado', 'SP'),
('Douradoquara', 'MG'),
('Dourados', 'MS'),
('Doutor Camargo', 'PR'),
('Doutor Maurício Cardoso', 'RS'),
('Doutor Pedrinho', 'SC'),
('Doutor Ricardo', 'RS'),
('Doutor Severiano', 'RN'),
('Doutor Ulysses', 'PR'),
('Dom Basílio', 'BA'),
('Dom Bosco', 'MG'),
('Dom Cavati', 'MG'),
('Dom Eliseu', 'PA'),
('Dom Expedito Lopes', 'PI'),
('Dom Feliciano', 'RS'),
('Dom Inocêncio', 'PI'),
('Dom Joaquim', 'MG'),
('Dom Macedo Costa', 'BA'),
('Dom Pedro', 'MA'),
('Dom Pedro de Alcântara', 'RS'),
('Dom Silverio', 'MG'),
('Dom Viçoso', 'MG'),
('Duas Barras', 'RJ'),
('Duas Estradas', 'PB'),
('Dumont', 'SP'),
(' dinâmica', 'TO'),
('Durandé', 'MG'),
('Echaporã', 'SP'),
('Ecoporanga', 'ES'),
('Edealina', 'GO'),
('Edéia', 'GO'),
('Eirunepé', 'AM'),
('Eldorado', 'MS'),
('Eldorado', 'SP'),
('Eldorado do Sul', 'RS'),
('Elesbão Veloso', 'PI'),
('Elias Fausto', 'SP'),
('Elisiário', 'SP'),
('Eliseu Martins', 'PI'),
('Embaúba', 'SP'),
('Embu das Artes', 'SP'),
('Embu-Guaçu', 'SP'),
('Emilianópolis', 'SP'),
('Encantado', 'RS'),
('Encanto', 'RN'),
('Encruzilhada', 'BA'),
('Encruzilhada do Sul', 'RS'),
('Enéas Marques', 'PR'),
('Engenheiro Beltrão', 'PR'),
('Engenheiro Caldas', 'MG'),
('Engenheiro Coêlho', 'SP'),
('Engenheiro Navarro', 'MG'),
('Engenheiro Paulo de Frontin', 'RJ'),
('Entre Rios', 'BA'),
('Entre Rios de Minas', 'MG'),
('Entre Rios do Oeste', 'PR'),
('Entre Rios do Sul', 'RS'),
('Entre Folhas', 'MG'),
('Entre Ijuís', 'RS'),
('Envira', 'AM'),
('Epitaciolândia', 'AC'),
('Equador', 'RN'),
('Erebango', 'RS'),
('Erechim', 'RS'),
('Ererê', 'CE'),
('Érico Cardoso', 'BA'),
('Ermo', 'SC'),
('Erval Grande', 'RS'),
('Erval Seco', 'RS'),
('Ervalia', 'MG'),
('Esmeralda', 'RS'),
('Esmeraldas', 'MG'),
('Esperança', 'PB'),
('Esperança Nova', 'PR'),
('Esperança do Sul', 'RS'),
('Esperantina', 'PI'),
('Esperantina', 'TO'),
('Espigão Alto do Iguaçu', 'PR'),
('Espigão D''Oeste', 'RO'),
('Espinosa', 'MG'),
('Espírito Santo', 'RN'),
('Espírito Santo do Dourado', 'MG'),
('Espírito Santo do Pinhal', 'SP'),
('Espírito Santo do Turvo', 'SP'),
('Esplanada', 'BA'),
('Estância', 'SE'),
('Estância Velha', 'RS'),
('Esteio', 'RS'),
('Estiva', 'MG'),
('Estiva Gerbi', 'SP'),
('Estreito', 'MA'),
('Estrela', 'RS'),
('Estrela D''Oeste', 'SP'),
('Estrela de Alagoas', 'AL'),
('Estrela do Indaiá', 'MG'),
('Estrela do Norte', 'GO'),
('Estrela do Norte', 'SP'),
('Estrela do Sul', 'MG'),
('Estrela Dalva', 'MG'),
('Euclides da Cunha', 'BA'),
('Euclides da Cunha Paulista', 'SP'),
('Eunápolis', 'BA'),
('Eusébio', 'CE'),
('Extrema', 'MG'),
('Extremoz', 'RN'),
('Exu', 'PE'),
('Fagundes', 'PB'),
('Fagundes Varela', 'RS'),
('Faina', 'GO'),
('Fama', 'MG'),
('Farias Brito', 'CE'),
('Faro', 'PA'),
('Farol', 'PR'),
('Farroupilha', 'RS'),
('Fartura', 'SP'),
('Fartura do Piauí', 'PI'),
('Faxinal', 'PR'),
('Faxinal do Soturno', 'RS'),
('Faxinal dos Guedes', 'SC'),
('Faxinalzinho', 'RS'),
('Fazenda Nova', 'GO'),
('Fazenda Rio Grande', 'PR'),
('Felício dos Santos', 'MG'),
('Felisburgo', 'MG'),
('Felixlândia', 'MG'),
('Feliz', 'RS'),
('Feliz Deserto', 'AL'),
('Feliz Natal', 'MT'),
('Fênix', 'PR'),
('Fernandes Pinheiro', 'PR'),
('Fernandes Tourinho', 'MG'),
('Fernando de Noronha', 'PE'),
('Fernando Falcão', 'MA'),
('Fernando Pedroza', 'RN'),
('Fernandópolis', 'SP'),
('Fernando Prestes', 'SP'),
('Fernão', 'SP'),
('Ferraz de Vasconcelos', 'SP'),
('Ferrazópolis', 'MG'),
('Ferreira Gomes', 'AP'),
('Ferros', 'MG'),
('Fervedouro', 'MG'),
('Figueira', 'PR'),
('Figueirópolis', 'TO'),
('Figueirópolis D''Oeste', 'MT'),
('Filadélfia', 'BA'),
('Filadélfia', 'TO'),
('Firminópolis', 'GO'),
('Flexeiras', 'AL'),
('Flor da Serra do Sul', 'PR'),
('Florânia', 'RN'),
('Flora Rica', 'SP'),
('Floraí', 'PR'),
('Floriano', 'PI'),
('Floriano Peixoto', 'RS'),
('Florianópolis', 'SC'),
('Floreal', 'SP'),
('Flores', 'PE'),
('Flores da Cunha', 'RS'),
('Flores de Goiás', 'GO'),
('Flores do Piauí', 'PI'),
('Florestal', 'MG'),
('Floresta', 'PE'),
('Floresta', 'PR'),
('Floresta Azul', 'BA'),
('Florestópolis', 'PR'),
('Florínia', 'SP'),
('Fonte Boa', 'AM'),
('Formiga', 'MG'),
('Formosa', 'GO'),
('Formosa da Serra Negra', 'MA'),
('Formosa do Rio Preto', 'BA'),
('Formosa do Sul', 'SC'),
('Formoso', 'GO'),
('Formoso', 'MG'),
('Forquilhinha', 'SC'),
('Fortaleza', 'CE'),
('Fortaleza de Minas', 'MG'),
('Fortaleza do Tabocão', 'TO'),
('Fortaleza dos Valos', 'RS'),
('Fortim', 'CE'),
('Foz do Iguaçu', 'PR'),
('Foz do Jordão', 'PR'),
('Fraiburgo', 'SC'),
('Franca', 'SP'),
('Francinópolis', 'PI'),
('Francisco Alves', 'PR'),
('Francisco Ayres', 'PI'),
('Francisco Badaró', 'MG'),
('Francisco Beltrão', 'PR'),
('Francisco Dantas', 'RN'),
('Francisco Dumont', 'MG'),
('Francisco Macedo', 'PI'),
('Francisco Morato', 'SP'),
('Francisco Santos', 'PI'),
('Franco da Rocha', 'SP'),
('Frecheirinha', 'CE'),
('Frederico Westphalen', 'RS'),
('Frei Gaspar', 'MG'),
('Frei Inocêncio', 'MG'),
('Frei Lagonegro', 'MG'),
('Frei Martinho', 'PB'),
('Frei Miguelinho', 'PE'),
('Frei Paulo', 'SE'),
('Freixoeira', 'CE'),
('Frontal', 'MG'),
('Frutal', 'MG'),
('Fruta de Leite', 'MG'),
('Frutuoso Gomes', 'RN'),
('Fundão', 'ES'),
('Funilândia', 'MG'),
('Furtado', 'PI'),
('Gabriel Monteiro', 'SP'),
('Gado Bravo', 'PB'),
('Gaião', 'PE'),
('Galinhos', 'RN'),
('Galvão', 'SC'),
('Gameleira', 'PE'),
('Gameleira de Goiás', 'GO'),
('Gameleiras', 'MG'),
('Gandu', 'BA'),
('Garabito', 'SC'),
('Gararu', 'SE'),
('Garça', 'SP'),
('Garibaldi', 'RS'),
('Garopaba', 'SC'),
('Garuva', 'SC'),
('Gaspar', 'SC'),
('Gastão Vidigal', 'SP'),
('Gaúcha do Norte', 'MT'),
('Gaurama', 'RS'),
('Gavião', 'BA'),
('Geminiano', 'PI'),
('General Carneiro', 'MT'),
('General Carneiro', 'PR'),
('General Câmara', 'RS'),
('General Maynard', 'SE'),
('General Salgado', 'SP'),
('General Sampaio', 'CE'),
('Gentil', 'RS'),
('Gentio do Ouro', 'BA'),
('Getulina', 'SP'),
('Getúlio Vargas', 'RS'),
('Giruá', 'RS'),
('Glória', 'BA'),
('Glória de Dourados', 'MS'),
('Glória do Goitá', 'PE'),
('Glória D''Oeste', 'MT'),
('Godofredo Filho', 'MA'),
('Godoy Moreira', 'PR'),
('Goiabeira', 'MG'),
('Goianá', 'MG'),
('Goianésia', 'GO'),
('Goianésia do Pará', 'PA'),
('Goiânia', 'GO'),
('Goianinha', 'RN'),
('Goianira', 'GO'),
('Goianorte', 'TO'),
('Goiás', 'GO'),
('Goiatins', 'TO'),
('Goiatuba', 'GO'),
('Goioerê', 'PR'),
('Goioxim', 'PR'),
('Gonçalves', 'MG'),
('Gonçalves Dias', 'MA'),
('Gongogi', 'BA'),
('Gonzaga', 'MG'),
('Gordinho', 'PE'),
('Governador Archer', 'MA'),
('Governador Celso Ramos', 'SC'),
('Governador Dix-Sept Rosado', 'RN'),
('Governador Edison Lobão', 'MA'),
('Governador Eugênio Barros', 'MA'),
('Governador Jorge Teixeira', 'RO'),
('Governador Lindenberg', 'ES'),
('Governador Luiz Rocha', 'MA'),
('Governador Mangabeira', 'BA'),
('Governador Nunes Freire', 'MA'),
('Governador Valadares', 'MG'),
('Graça', 'CE'),
('Graça Aranha', 'MA'),
('Graccho Cardoso', 'SE'),
('Gracho Cardoso', 'TO'),
('Grajaú', 'MA'),
('Gramado', 'RS'),
('Gramado dos Loureiros', 'RS'),
('Gramado Xavier', 'RS'),
('Grandes Rios', 'PR'),
('Granja', 'CE'),
('Granjeiro', 'CE'),
('Grão Mogol', 'MG'),
('Grão Pará', 'SC'),
('Gravatá', 'PE'),
('Gravataí', 'RS'),
('Groaíras', 'CE'),
('Grossos', 'RN'),
('Grupiara', 'MG'),
('Guabiruba', 'SC'),
('Guaiúba', 'CE'),
('Guajará', 'AM'),
('Guajará-Mirim', 'RO'),
('Guamiranga', 'PR'),
('Guanambi', 'BA'),
('Guanhães', 'MG'),
('Guapé', 'MG'),
('Guapimirim', 'RJ'),
('Guapo', 'SP'),
('Guaporé', 'RS'),
('Guarabira', 'PB'),
('Guaraci', 'PR'),
('Guaraci', 'SP'),
('Guaraciaba', 'MG'),
('Guaraciaba', 'SC'),
('Guaraciaba do Norte', 'CE'),
('Guaraciama', 'MG'),
('Guaraí', 'TO'),
('Guaraíta', 'GO'),
('Guarani', 'MG'),
('Guarani das Missões', 'RS'),
('Guarani de Goiás', 'GO'),
('Guaraniaçu', 'PR'),
('Guarani D''Oeste', 'SP'),
('Guaranta', 'SP'),
('Guarantã', 'MT'),
('Guarapari', 'ES'),
('Guarapuava', 'PR'),
('Guaraqueçaba', 'PR'),
('Guarará', 'MG'),
('Guararapes', 'SP'),
('Guararema', 'SP'),
('Guaratinga', 'BA'),
('Guaratinguetá', 'SP'),
('Guaratuba', 'PR'),
('Guarda-Mor', 'MG'),
('Guareí', 'SP'),
('Guariba', 'SP'),
('Guaribas', 'PI'),
('Guarujá', 'SP'),
('Guarujá do Sul', 'SC'),
('Guarulhos', 'SP'),
('Guarvelândia', 'GO'),
('Guaxupé', 'MG'),
('Guia Lopes da Laguna', 'MS'),
('Guiana', 'PR'),
('Guimarães', 'MA'),
('Guimarânia', 'MG'),
('Guiricema', 'MG'),
('Guiratinga', 'MT'),
('Gurinhatã', 'MG'),
('Gurjão', 'PB'),
('Gurupá', 'PA'),
('Gurupi', 'TO'),
('Harmonia', 'RS'),
('Heitoraí', 'GO'),
('Heliodora', 'MG'),
('Heliópolis', 'BA'),
('Herculândia', 'SP'),
('Herval', 'RS'),
('Herval D''Oeste', 'SC'),
('Herverilândia', 'GO'),
('Hidrolândia', 'CE'),
('Hidrolândia', 'GO'),
('Hidrolina', 'GO'),
('Holambra', 'SP'),
('Honório Serpa', 'PR'),
('Horizonte', 'CE'),
('Horizontina', 'RS'),
('Hortolândia', 'SP'),
('Hugo Napoleão', 'PI'),
('Humaitá', 'AM'),
('Humaitá', 'RS'),
('Hulha Negra', 'RS'),
('Iacanga', 'SP'),
('Iaciara', 'GO'),
('Iapu', 'MG'),
('Iaras', 'SP'),
('Iati', 'PE'),
('Ibaretama', 'CE'),
('Ibaté', 'SP'),
('Ibateguara', 'AL'),
('Ibaiti', 'PR'),
('Ibicoara', 'BA'),
('Ibicuí', 'BA'),
('Ibicuitinga', 'CE'),
('Ibimirim', 'PE'),
('Ibiá', 'MG'),
('Ibiapina', 'CE'),
('Ibiara', 'PB'),
('Ibiassucê', 'BA'),
('Ibicaraí', 'BA'),
('Ibicaré', 'SC'),
('Ibipitanga', 'BA'),
('Ibiporã', 'PR'),
('Ibiquera', 'BA'),
('Ibiracatu', 'MG'),
('Ibiraci', 'MG'),
('Ibiraçu', 'ES'),
('Ibiraiaras', 'RS'),
('Ibirajuba', 'PE'),
('Ibirapinhã', 'PR'),
('Ibirapuã', 'BA'),
('Ibirapuitã', 'RS'),
('Ibirarema', 'SP'),
('Ibirataia', 'BA'),
('Ibirité', 'MG'),
('Ibirubá', 'RS'),
('Ibiruitiba', 'PR'),
('Ibitiara', 'BA'),
('Ibitinga', 'SP'),
('Ibitirama', 'ES'),
('Ibitira', 'MG'),
('Ibituruna', 'MG'),
('Ibiúna', 'SP'),
('Ibo', 'BA'),
('Ibotirama', 'BA'),
('Icaiara', 'CE'),
('Icém', 'SP'),
('Ichu', 'BA'),
('Icó', 'CE'),
('Iconha', 'ES'),
('Ielmo Marinho', 'RN'),
('Iepê', 'SP'),
('Igaci', 'AL'),
('Igarapé-Açu', 'PA'),
('Igarapé do Meio', 'MA'),
('Igarapé-Miri', 'PA'),
('Igarapé Grande', 'MA'),
('Igaratinga', 'MG'),
('Igaratá', 'SP'),
('Igrapiúna', 'BA'),
('Igreja Nova', 'AL'),
('Igrejinha', 'RS'),
('Iguaba Grande', 'RJ'),
('Iguaí', 'BA'),
('Iguape', 'SP'),
('Iguaraci', 'PE'),
('Iguatama', 'MG'),
('Iguatemi', 'MS'),
('Iguatu', 'CE'),
('Iguatu', 'PR'),
('Ijaci', 'MG'),
('Ijuí', 'RS'),
('Ilha Comprida', 'SP'),
('Ilha das Flores', 'SE'),
('Ilha de Itamaracá', 'PE'),
('Ilha Grande', 'PI'),
('Ilha Solteira', 'SP'),
('Ilhabela', 'SP'),
('Ilhéus', 'BA'),
('Ilhota', 'SC'),
('Imaculada', 'PB'),
('Imbaú', 'PR'),
('Imbituba', 'SC'),
('Imbituva', 'PR'),
('Imbuia', 'SC'),
('Inajá', 'PE'),
('Inajá', 'PR'),
('Inconfidentes', 'MG'),
('Indaiabira', 'MG'),
('Indaial', 'SC'),
('Indaiatuba', 'SP'),
('Independência', 'CE'),
('Independência', 'RS'),
('Indiana', 'SP'),
('Indianópolis', 'MG'),
('Indianópolis', 'PR'),
('Indiara', 'GO'),
('Indiaporã', 'SP'),
('Ingaí', 'MG'),
('Ingazeira', 'PE'),
('Inhacorá', 'RS'),
('Inhambupe', 'BA'),
('Inhapi', 'AL'),
('Inhaúma', 'MG'),
('Inhupeba', 'CE'),
('Inimutaba', 'MG'),
('Inhangapi', 'PA'),
('Inhumas', 'GO'),
('Inocência', 'MS'),
('Inove', 'GO'),
('Inúbia Paulista', 'SP'),
('Ipanema', 'MG'),
('Ipaba', 'MG'),
('Ipameri', 'GO'),
('Ipaumirim', 'CE'),
('Ipaguaçu', 'RN'),
('Ipatinga', 'MG'),
('Ipaussu', 'SP'),
('Ipava', 'SP'),
('Ipeúna', 'SP'),
('Ipixuna', 'AM'),
('Ipixuna do Pará', 'PA'),
('Iporá', 'GO'),
('Iporanga', 'SP'),
('Iporã', 'PR'),
('Ipu', 'CE'),
('Ipuã', 'SP'),
('Ipuaçu', 'SC'),
('Ipubi', 'PE'),
('Ipueira', 'RN'),
('Ipueiras', 'CE'),
('Ipuiúna', 'MG'),
('Iracema', 'CE'),
('Iracema', 'RR'),
('Iracemápolis', 'SP'),
('Iraceminha', 'SC'),
('Iraí', 'RS'),
('Iraí de Minas', 'MG'),
('Irajuba', 'BA'),
('Iramaia', 'BA'),
('Iranduba', 'AM'),
('Irani', 'SC'),
('Irapuã', 'SP'),
('Irapuru', 'SP'),
('Iraquara', 'BA'),
('Irará', 'BA'),
('Irecê', 'BA'),
('Iretama', 'PR'),
('Irinópolis', 'SC'),
('Irituia', 'PA'),
('Irlanda', 'SP'),
('Irópolis', 'CE'),
('Isaías Coelho', 'PI'),
('Itabaiana', 'PB'),
('Itabapoana', 'RJ'),
('Itaberaí', 'GO'),
('Itabirinha de Mantena', 'MG'),
('Itacaranha', 'PR'),
('Itacurubi', 'RS'),
('Itajuba', 'MG'),
('Ituaba', 'RS'),
('Itapecerica', 'MG'),
('Itapecerica da Serra', 'SP'),
('Itapé', 'BA'),
('Itapora do Tocantins', 'TO'),
('Itauçu', 'GO'),
('Itaqui', 'BA'),
('Itinga', 'MG'),
('Itinga do Maranhão', 'MA'),
('Itirapina', 'SP'),
('Itirapuã', 'SP'),
('Itiruçu', 'BA'),
('Itu de Minas', 'MG'),
('Ituí', 'PR'),
('Itinga', 'MA'),
('Ituran', 'PR'),
('Itá', 'SC'),
('Itaguari', 'GO'),
('Itapebi', 'BA'),
('Itapororoca', 'PB'),
('Itarantim', 'BA'),
('Itatim', 'BA'),
('Itirussu', 'MG'),
('Itabaiana', 'SE'),
('Itabaianinha', 'SE'),
('Itabira', 'MG'),
('Itabirinha', 'MG'),
('Itabirito', 'MG'),
('Itabuna', 'BA'),
('Itacajá', 'TO'),
('Itacambira', 'MG'),
('Itacarambi', 'MG'),
('Itacaré', 'BA'),
('Itacoatiara', 'AM'),
('Itacuruba', 'PE'),
('Itaetê', 'BA'),
('Itagi', 'BA'),
('Itagibá', 'BA'),
('Itagimirim', 'BA'),
('Itaguaçu', 'ES'),
('Itaguaçu da Bahia', 'BA'),
('Itaguajé', 'PR'),
('Itaguara', 'MG'),
('Itaguaru', 'CE'),
('Itaguatins', 'TO'),
('Itaí', 'SP'),
('Itaiópolis', 'SC'),
('Itaipé', 'MG'),
('Itaipulândia', 'PR'),
('Itajá', 'GO'),
('Itajá', 'RN'),
('Itajaí', 'SC'),
('Itajobi', 'SP'),
('Itaju', 'SP'),
('Itajubá', 'MG'),
('Itajuípe', 'BA'),
('Itamaracá', 'PE'),
('Itamaraju', 'BA'),
('Itamarandiba', 'MG'),
('Itamarati', 'AM'),
('Itamari', 'BA'),
('Itambacuri', 'MG'),
('Itambaracá', 'PR'),
('Itambé', 'BA'),
('Itambé', 'PE'),
('Itambé', 'PR'),
('Itamogi', 'MG'),
('Itamonte', 'MG'),
('Itanagra', 'BA'),
('Itanhangá', 'MT'),
('Itanhaém', 'SP'),
('Itanhandu', 'MG'),
('Itanhomi', 'MG'),
('Ituacu', 'CE'),
('Ituano', 'SP'),
('Itapaci', 'GO'),
('Itapecuru Mirim', 'MA'),
('Itapejara D''Oeste', 'PR'),
('Itapema', 'SC'),
('Itapemirim', 'ES'),
('Itaperuçu', 'PR'),
('Itaperuna', 'RJ'),
('Itapetim', 'PE'),
('Itapetininga', 'SP'),
('Itapiúna', 'CE'),
('Itapicuru', 'BA'),
('Itapipoca', 'CE'),
('Itapira', 'SP'),
('Itapiranga', 'AM'),
('Itapiranga', 'SC'),
('Itapiratins', 'TO'),
('Itapissuma', 'PE'),
('Itapirapuã', 'GO'),
('Itápolis', 'SP'),
('Itaporanga', 'PB'),
('Itaporanga', 'SP'),
('Itaporanga D''Ajuda', 'SE'),
('Itaporã', 'MS'),
('Itaporã do Tocantins', 'TO'),
('Itapuã do Oeste', 'RO'),
('Itapuí', 'SP'),
('Itapuranga', 'GO'),
('Itaquara', 'BA'),
('Itaqui', 'RS'),
('Itaquiraí', 'MS'),
('Itaquitinga', 'PE'),
('Itarana', 'ES'),
('Itararé', 'SP'),
('Itariri', 'SP'),
('Itarumã', 'GO'),
('Itati', 'RS'),
('Itatiaia', 'RJ'),
('Itatiba', 'SP'),
('Itatira', 'CE'),
('Itatuba', 'PB'),
('Itaú', 'RN'),
('Itaú de Minas', 'MG'),
('Itaueira', 'PI'),
('Itaúna', 'MG'),
('Itaúna do Sul', 'PR'),
('Itaverava', 'MG'),
('Itiúba', 'BA'),
('Itobi', 'SP'),
('Itororó', 'BA'),
('Itu', 'SP'),
('Ituaçu', 'BA'),
('Ituberá', 'BA'),
('Ituiutaba', 'MG'),
('Itumirim', 'MG'),
('Itumbiara', 'GO'),
('Itupeva', 'SP'),
('Iturama', 'MG'),
('Iturama do Sul', 'PR'),
('Itutinga', 'MG'),
('Ituverava', 'SP'),
('Iuiú', 'BA'),
('Iúna', 'ES'),
('Ivaiporã', 'PR'),
('Ivaí', 'PR'),
('Ivaí do Sul', 'PR'),
('Ivaté', 'PR'),
('Ivatuba', 'PR'),
('Ivinhema', 'MS'),
('Ivolândia', 'GO'),
('Ivorá', 'RS'),
('Ivoti', 'RS'),
('Jaboticaba', 'RS'),
('Jaboticabal', 'SP'),
('Jaçanã', 'RN'),
('Jacaraci', 'BA'),
('Jacaraú', 'PB'),
('Jacarezinho', 'PR'),
('Jaci', 'SP'),
('Jacinto', 'MG'),
('Jacinto Machado', 'SC'),
('Jacobina', 'BA'),
('Jacobina do Piauí', 'PI'),
('Jacuí', 'MG'),
('Jacuípe', 'AL'),
('Jacupiranga', 'SP'),
('Jacundá', 'PA'),
('Jaguapitã', 'PR'),
('Jaguaraçu', 'MG'),
('Jaguarão', 'RS'),
('Jaguaré', 'ES'),
('Jaguaretama', 'CE'),
('Jaguari', 'RS'),
('Jaguariaíva', 'PR'),
('Jaguaripe', 'BA'),
('Jaguaribara', 'CE'),
('Jaguaribe', 'CE'),
('Jaguariúna', 'SP'),
('Jaguaquara', 'BA'),
('Jales', 'SP'),
('Jamapará', 'RJ'),
('Jambeiro', 'SP'),
('Jampruca', 'MG'),
('Janaúba', 'MG'),
('Jandaia', 'GO'),
('Jandaia do Sul', 'PR'),
('Jandaíra', 'BA'),
('Jandaíra', 'RN'),
('Janiópolis', 'PR'),
('Januária', 'MG'),
('Japaraíba', 'MG'),
('Japaratinga', 'AL'),
('Japira', 'PR'),
('Japoatã', 'SE'),
('Japonvar', 'MG'),
('Japurá', 'AM'),
('Japurá', 'PR'),
('Jaquirana', 'RS'),
('Jaraguá', 'GO'),
('Jaraguá do Sul', 'SC'),
('Jaraguari', 'MS'),
('Jardim', 'CE'),
('Jardim', 'MS'),
('Jardim Alegre', 'PR'),
('Jardim de Angicos', 'RN'),
('Jardim de Piranhas', 'RN'),
('Jardim do Seridó', 'RN'),
('Jardim Olinda', 'PR'),
('Jardim Nova Esperança', 'MT'),
('Jardim Paulista', 'SP'),
('Jardim Pioneiro', 'PR'),
('Jardinópolis', 'SP'),
('Jaru', 'RO'),
('Jataí', 'GO'),
('Jataizinho', 'PR'),
('Jati', 'CE'),
('Jaú', 'SP'),
('Jaujacu', 'PR'),
('Jequiá da Praia', 'AL'),
('Jequié', 'BA'),
('Jequitaí', 'MG'),
('Jequitibá', 'ES'),
('Jequitinhonha', 'MG'),
('Jeremoabo', 'BA'),
('Jericó', 'PB'),
('Jeriquara', 'SP'),
('Jerumenha', 'PI'),
('Jesuítas', 'PR'),
('Jesúpolis', 'GO'),
('Ji-Paraná', 'RO'),
('Jijoca de Jericoacoara', 'CE'),
('Joana D''Arc', 'MG'),
('Joanes', 'PA'),
('João Alfredo', 'PE'),
('João Câmara', 'RN'),
('João Dias', 'RN'),
('João Dourado', 'BA'),
('João Lisboa', 'MA'),
('João Monlevade', 'MG'),
('João Neiva', 'ES'),
('João Pessoa', 'PB'),
('João Ramalho', 'SP'),
('Joaquim Felício', 'MG'),
('Joaquim Gomes', 'AL'),
('Joaquim Pires', 'PI'),
('Joca Marques', 'PI'),
('Joca Marques', 'RN'),
('Jóia', 'RS'),
('Joinville', 'SC'),
('Jordão', 'AC'),
('Jordão', 'PR'),
('José Boiteux', 'SC'),
('José Bonifácio', 'SP'),
('José de Freitas', 'PI'),
('José Gonçalves de Minas', 'MG'),
('José Raydan', 'MG'),
('Josenópolis', 'MG'),
('Jovita', 'CE'),
('Juatuba', 'MG'),
('Jucás', 'CE'),
('Jucati', 'PE'),
('Jucurutu', 'RN'),
('Juína', 'MT'),
('Juiz de Fora', 'MG'),
('Júlio Borges', 'PI'),
('Júlio de Castilhos', 'RS'),
('Jundiaí', 'SP'),
('Jundiaí do Sul', 'PR'),
('Jundiá', 'AL'),
('Jundiá', 'RN'),
('Junqueiro', 'AL'),
('Junqueirópolis', 'SP'),
('Jupi', 'PE'),
('Jupira', 'PR'),
('Juru', 'PB'),
('Juruá', 'AM'),
('Jurucê', 'PR'),
('Juruena', 'MT'),
('Juruti', 'PA'),
('Jutaí', 'AM'),
('Jutai', 'AM'),
('Juti', 'MS'),
('Lacerdópolis', 'SC'),
('Ladainha', 'MG'),
('Ladário', 'MS'),
('Lagamar', 'MG'),
('Lagarto', 'SE'),
('Lages', 'SC'),
('Lagoa', 'PB'),
('Lagoa Alegre', 'PI'),
('Lagoa Bonita do Sul', 'RS'),
('Lagoa da Canoa', 'AL'),
('Lagoa da Confusão', 'TO'),
('Lagoa da Prata', 'MG'),
('Lagoa D''Anta', 'RN'),
('Lagoa de Dentro', 'PB'),
('Lagoa de Itaenga', 'PE'),
('Lagoa de Pedras', 'RN'),
('Lagoa de São Francisco', 'PI'),
('Lagoa de Velhos', 'RN'),
('Lagoa do Carro', 'PE'),
('Lagoa do Mato', 'MA'),
('Lagoa do Ouro', 'PE'),
('Lagoa do Piauí', 'PI'),
('Lagoa do Sítio', 'PI'),
('Lagoa do Tocantins', 'TO'),
('Lagoa dos Gatos', 'PE'),
('Lagoa dos Patos', 'MG'),
('Lagoa dos Rodrigues', 'MA'),
('Lagoa dos Três Cantos', 'RS'),
('Lagoa Grande', 'MG'),
('Lagoa Grande', 'PE'),
('Lagoa Grande do Maranhão', 'MA'),
('Lagoa Nova', 'RN'),
('Lagoa Salgada', 'RN'),
('Lagoa Santa', 'GO'),
('Lagoa Santa', 'MG'),
('Lagoa Seca', 'PB'),
('Lagoa Vermelha', 'RS'),
('Lagoinha', 'SP'),
('Lagoinha do Piauí', 'PI'),
('Lajedo', 'PE'),
('Lajedinho', 'BA'),
('Lajedo do Tabocal', 'BA'),
('Lajeado', 'RS'),
('Lajeado do Bugre', 'RS'),
('Lajeado Grande', 'SC'),
('Lajeado Novo', 'MA'),
('Lajedão', 'BA'),
('Lajeosa', 'MG'),
('Lajes', 'RN'),
('Lajes Pintadas', 'RN'),
('Lamarão', 'BA'),
('Lambari', 'MG'),
('Lambari D''Oeste', 'MT'),
('Lamim', 'MG'),
('Landri Sales', 'PI'),
('Lapa', 'PR'),
('Laranjal', 'MG'),
('Laranjal', 'PR'),
('Laranjal do Jari', 'AP'),
('Laranjeiras', 'SE'),
('Laranjeiras do Sul', 'PR'),
('Lassance', 'MG'),
('Lastro', 'PB'),
('Laurentino', 'SC'),
('Lavandeira', 'TO'),
('Lavras', 'MG'),
('Lavras da Mangabeira', 'CE'),
('Lavras do Sul', 'RS'),
('Lavrinhas', 'SP'),
('Leandro Ferreira', 'MG'),
('Lebon Régis', 'SC'),
('Leme', 'SP'),
('Leme do Prado', 'MG'),
('Lençóis', 'BA'),
('Lençóis Paulista', 'SP'),
('Leoberto Leal', 'SC'),
('Leopoldina', 'MG'),
('Liberato Salzano', 'RS'),
('Liberdade', 'MG'),
('Licínio de Almeida', 'BA'),
('Lidianópolis', 'PR'),
('Lima Campos', 'MA'),
('Lima Duarte', 'MG'),
('Limeira', 'SP'),
('Limeira D''Oeste', 'MG'),
('Limoeiro', 'PE'),
('Limoeiro do Ajuru', 'PA'),
('Limoeiro do Norte', 'CE'),
('Lindoia', 'SP'),
('Lindolfo Collor', 'RS'),
('Lindolfo Collor', 'PR'),
('Lins', 'SP'),
('Linha Nova', 'RS'),
('Linhares', 'ES'),
('Livramento', 'PB'),
('Livramento de Nossa Senhora', 'BA'),
('Lizarda', 'TO'),
('Loanda', 'PR'),
('Lobato', 'PR'),
('Logradouro', 'PB'),
('Londrina', 'PR'),
('Lontra', 'MG'),
('Lontras', 'SC'),
('Lorena', 'SP'),
('Loreto', 'MA'),
('Lourdes', 'SP'),
('Louveira', 'SP'),
('Lucas do Rio Verde', 'MT'),
('Luís Antônio', 'SP'),
('Luís Correia', 'PI'),
('Luís Eduardo Magalhães', 'BA'),
('Luislândia', 'MG'),
('Luminárias', 'MG'),
('Lunardelli', 'PR'),
('Lupércio', 'SP'),
('Lupionópolis', 'PR'),
('Lutécia', 'SP'),
('Luz', 'MG'),
('Luzerna', 'SC'),
('Luziânia', 'GO'),
('Macacari', 'AM'),
('Macaparana', 'PE'),
('Macaé', 'RJ'),
('Macajuba', 'BA'),
('Macambira', 'SE'),
('Macaubal', 'SP'),
('Macaúbas', 'BA'),
('Macedônia', 'SP'),
('Machadinho', 'RS'),
('Machadinho D''Oeste', 'RO'),
('Machados', 'PE'),
('Machakal', 'MG'),
('Macuco', 'RJ'),
('Macururé', 'BA'),
('Madalena', 'CE'),
('Madeiro', 'PI'),
('Madre de Deus', 'BA'),
('Madre de Deus de Minas', 'MG'),
('Mãe D''Água', 'PB'),
('Maetinga', 'BA'),
('Magalhães de Almeida', 'MA'),
('Magda', 'SP'),
('Magé', 'RJ'),
('Malacacheta', 'MG'),
('Malhada', 'BA'),
('Malhada de Pedras', 'BA'),
('Malhada dos Bois', 'SE'),
('Malhador', 'SE'),
('Mallet', 'PR'),
('Malta', 'PB'),
('Mamanguape', 'PB'),
('Mambaí', 'GO'),
('Mamborê', 'PR'),
('Mamonas', 'MG'),
('Manacapuru', 'AM'),
('Manaíra', 'PB'),
('Manaquiri', 'AM'),
('Manari', 'PE'),
('Manaus', 'AM'),
('Mandaguaçu', 'PR'),
('Mandaguari', 'PR'),
('Mandirituba', 'PR'),
('Manfrinópolis', 'PR'),
('Manga', 'MG'),
('Manhuaçu', 'MG'),
('Manhumirim', 'MG'),
('Manicoré', 'AM'),
('Manitoba', 'PR'),
('Mantena', 'MG'),
('Mantenópolis', 'ES'),
('Maquiné', 'RS'),
('Mar de Espanha', 'MG'),
('Mar Vermelho', 'AL'),
('Maraã', 'AM'),
('Marabá', 'PA'),
('Marabá Paulista', 'SP'),
('Maracanaú', 'CE'),
('Maracaí', 'SP'),
('Maracajá', 'SC'),
('Maracaju', 'MS'),
('Maracás', 'BA'),
('Maragogi', 'AL'),
('Maragogipe', 'BA'),
('Maraial', 'PE'),
('Marajá do Sena', 'MA'),
('Marapanim', 'PA'),
('Marapoama', 'SP'),
('Marataízes', 'ES'),
('Marau', 'RS'),
('Maraú', 'BA'),
('Marcação', 'PB'),
('Marcelândia', 'MT'),
('Marcelino Ramos', 'RS'),
('Marcelino Vieira', 'RN'),
('Marcionílio Souza', 'BA'),
('Marco', 'CE'),
('Marcos Parente', 'PI'),
('Março', 'RS'),
('Marechal Deodoro', 'AL'),
('Marechal Floriano', 'ES'),
('Marechal Cândido Rondon', 'PR'),
('Marechal Thaumaturgo', 'AC'),
('Mari', 'PB'),
('Maria da Fé', 'MG'),
('Maria Helena', 'PR'),
('Maria', 'RS'),
('Mariana', 'MG'),
('Mariana Pimentel', 'RS'),
('Marianópolis do Tocantins', 'TO'),
('Mariano Moro', 'RS'),
('Marianos', 'MG'),
('Mariápolis', 'SP'),
('Maribondo', 'AL'),
('Marilac', 'MG'),
('Marilândia', 'ES'),
('Marilândia do Sul', 'PR'),
('Marilena', 'PR'),
('Marília', 'SP'),
('Mariluz', 'PR'),
('Maringá', 'PR'),
('Marinópolis', 'GO'),
('Mariópolis', 'PR'),
('Maripá', 'PR'),
('Maripá de Minas', 'MG'),
('Marituba', 'PA'),
('Marliéria', 'MG'),
('Marmelópolis', 'MG'),
('Marques de Souza', 'RS'),
('Martinho Campos', 'MG'),
('Martins', 'RN'),
('Martins Soares', 'MG'),
('Maruim', 'SE'),
('Marumbi', 'PR'),
('Mascote', 'BA'),
('Massapê', 'CE'),
('Massapê do Piauí', 'PI'),
('Mata', 'RS'),
('Mata de São João', 'BA'),
('Mata Grande', 'AL'),
('Mata Roma', 'MA'),
('Mata Verde', 'MG'),
('Matão', 'SP'),
('Mataraca', 'PB'),
('Mateiros', 'TO'),
('Matelândia', 'PR'),
('Materlândia', 'MG'),
('Mateus Leme', 'MG'),
('Matina', 'BA'),
('Matinha', 'MA'),
('Matinhas', 'PB'),
('Mato Castelhano', 'RS'),
('Mato Leitão', 'RS'),
('Mato Queimado', 'RS'),
('Mato Rico', 'PR'),
('Mato Verde', 'MG'),
('Matões', 'MA'),
('Matões do Norte', 'MA'),
('Matrinchã', 'GO'),
('Matriz de Camaragibe', 'AL'),
('Maturéia', 'PB'),
('Matutina', 'MG'),
('Mauá', 'SP'),
('Mauá da Serra', 'PR'),
('Maués', 'AM'),
('Maurilândia', 'GO'),
('Maurilândia do Tocantins', 'TO'),
('Mauriti', 'CE'),
('Medianeira', 'PR'),
('Medina', 'MG'),
('Meleiro', 'SC'),
('Melgaço', 'PA'),
('Mendes', 'RJ'),
('Mendes Pimentel', 'MG'),
('Mentira', 'PA'),
('Mercês', 'MG'),
('Meruoca', 'CE'),
('Mesquita', 'MG'),
('Mesquita', 'RJ'),
('Messias', 'AL'),
('Messias Targino', 'RN'),
('Miguel Alves', 'PI'),
('Miguel Calmon', 'BA'),
('Miguelópolis', 'SP'),
('Milagres', 'BA'),
('Milagres do Maranhão', 'MA'),
('Milhã', 'CE'),
('Mimoso de Goiás', 'GO'),
('Mimoso do Sul', 'ES'),
('Minaçu', 'GO'),
('Minador do Negrão', 'AL'),
('Minas do Leão', 'RS'),
('Minas Novas', 'MG'),
('Minduri', 'MG'),
('Mineiros', 'GO'),
('Mineiros do Tietê', 'SP'),
('Ministro Andreazza', 'RO'),
('Mirabela', 'MG'),
('Miracema', 'RJ'),
('Miracema do Tocantins', 'TO'),
('Miradouro', 'MG'),
('Miracatu', 'SP'),
('Mira Estrela', 'SP'),
('Mirador', 'MA'),
('Mirador', 'PR'),
('Mirador', 'SC'),
('Mirandiba', 'PE'),
('Miranda', 'MS'),
('Miranda do Norte', 'MA'),
('Mirandópolis', 'SP'),
('Mirangaba', 'BA'),
('Miranorte', 'TO'),
('Mirante', 'BA'),
('Mirante da Serra', 'RO'),
('Mirassol', 'SP'),
('Mirassol D''Oeste', 'MT'),
('Mirim Doce', 'SC'),
('Mirinzal', 'MA'),
('Missal', 'PR'),
('Mocajuba', 'PA'),
('Moeda', 'MG'),
('Moema', 'MG'),
('Mogeiro', 'PB'),
('Mogi das Cruzes', 'SP'),
('Mogi Guaçu', 'SP'),
('Mogi Mirim', 'SP'),
('Moita Bonita', 'SE'),
('Moju', 'PA'),
('Mombiri', 'CE'),
('Momente', 'MG'),
('Mona', 'CE'),
('Monção', 'MA'),
('Mongaguá', 'SP'),
('Monjolos', 'MG'),
('Monsenhor Gil', 'PI'),
('Monsenhor Hipólito', 'PI'),
('Monsenhor Paulo', 'MG'),
('Montadas', 'PB'),
('Montanha', 'ES'),
('Montanhas', 'RN'),
('Montauri', 'RS'),
('Monte Alegre', 'PA'),
('Monte Alegre de Goiás', 'GO'),
('Monte Alegre de Minas', 'MG'),
('Monte Alegre do Piauí', 'PI'),
('Monte Alegre do Sul', 'SP'),
('Monte Alto', 'SP'),
('Monte Aprazível', 'SP'),
('Monte Azul', 'MG'),
('Monte Belo', 'MG'),
('Monte Carlo', 'SC'),
('Monte Carmelo', 'MG'),
('Monte Castelo', 'SC'),
('Monte das Gameleiras', 'RN'),
('Monte Horebe', 'PB'),
('Monte Mor', 'SP'),
('Monte Negro', 'RO'),
('Monte Santo', 'BA'),
('Monte Santo de Minas', 'MG'),
('Monte Sião', 'MG'),
('Monteiro', 'PB'),
('Monteirópolis', 'AL'),
('Montes Altos', 'MA'),
('Montes Claros', 'MG'),
('Montes Claros de Goiás', 'GO'),
('Montezuma', 'MG'),
('Montividiu', 'GO'),
('Montividiu do Norte', 'GO'),
('Morada Nova', 'CE'),
('Morada Nova de Minas', 'MG'),
('Morrinhos', 'CE'),
('Morrinhos', 'GO'),
('Morrinhos do Sul', 'RS'),
('Morro Agudo', 'SP'),
('Morro Agudo de Goiás', 'GO'),
('Morro Cabeça no Tempo', 'PI'),
('Morro da Fumaça', 'SC'),
('Morro do Chapéu', 'BA'),
('Morro do Chapéu do Piauí', 'PI'),
('Morro do Pilar', 'MG'),
('Morro Grande', 'SC'),
('Morro Redondo', 'RS'),
('Morro Reuter', 'RS'),
('Morros', 'MA'),
('Morte', 'BA'),
('Mostardas', 'RS'),
('Motuca', 'SP'),
('Mozarlândia', 'GO'),
('Muaná', 'PA'),
('Mucajaí', 'RR'),
('Mucambo', 'CE'),
('Mudas', 'PR'),
('Muçum', 'RS'),
('Mucugê', 'BA'),
('Mucuri', 'BA'),
('Muitos Capões', 'RS'),
('Muliterno', 'RS'),
('Mundo Novo', 'BA'),
('Mundo Novo', 'GO'),
('Mundo Novo', 'MS'),
('Munhoz', 'MG'),
('Munhoz de Melo', 'PR'),
('Muniz Ferreira', 'BA'),
('Muniz Freire', 'ES'),
('Murici', 'AL'),
('Murici dos Portelas', 'PI'),
('Muricilândia', 'TO'),
('Muritiba', 'BA'),
('Murutinga do Sul', 'SP'),
('Mutum', 'MG'),
('Mutunópolis', 'GO'),
('Muzambinho', 'MG'),
('Nacip Raydan', 'MG'),
('Nantes', 'SP'),
('Nanuque', 'MG'),
('Naque', 'MG'),
('Narandiba', 'SP'),
('Natal', 'RN'),
('Natalândia', 'MG'),
('Natividade', 'RJ'),
('Natividade', 'TO'),
('Natuba', 'PB'),
('Nazaré', 'BA'),
('Nazaré', 'TO'),
('Nazaré da Mata', 'PE'),
('Nazaré do Piauí', 'PI'),
('Nazareno', 'MG'),
('Nazarezinho', 'PB'),
('Nazária', 'PI'),
('Neópolis', 'SE'),
('Nepomuceno', 'MG'),
('Nerópolis', 'GO'),
('Nestor', 'MG'),
('Neves Paulista', 'SP'),
('Nhamundá', 'AM'),
('Nilo Peçanha', 'BA'),
('Nilópolis', 'RJ'),
('Nina Rodrigues', 'MA'),
('Ninheira', 'MG'),
('Niquelândia', 'GO'),
('Nísia Floresta', 'RN'),
('Niterói', 'RJ'),
('Nobres', 'MT'),
('Noelândia', 'MA'),
('Nonoai', 'RS'),
('Nordestina', 'BA'),
('Normandia', 'RR'),
('Norte da Cidade', 'MG'),
('Norton de Campos', 'MG'),
('Nova Alvorada', 'RS'),
('Nova Alvorada do Sul', 'MS'),
('Nova América', 'GO'),
('Nova América da Colina', 'PR'),
('Nova Andradina', 'MS'),
('Nova Aurora', 'GO'),
('Nova Aurora', 'PR'),
('Nova Bandeirantes', 'MT'),
('Nova Bassano', 'RS'),
('Nova Belém', 'MG'),
('Nova Boa Vista', 'RS'),
('Nova Brasilândia', 'MT'),
('Nova Brasilândia D''Oeste', 'RO'),
('Nova Bréscia', 'RS'),
('Nova Campina', 'SP'),
('Nova Canaã', 'BA'),
('Nova Canaã do Norte', 'MT'),
('Nova Candelária', 'RS'),
('Nova Cantu', 'PR'),
('Nova Castilho', 'SP'),
('Nova Erechim', 'SC'),
('Nova Esperança', 'PR'),
('Nova Esperança do Piriá', 'PA'),
('Nova Esperança do Sudoeste', 'PR'),
('Nova Esperança do Sul', 'RS'),
('Nova Europa', 'SP'),
('Nova Fátima', 'BA'),
('Nova Fátima', 'PR'),
('Nova Floresta', 'PB'),
('Nova Friburgo', 'RJ'),
('Nova Glória', 'GO'),
('Nova Guarita', 'MT'),
('Nova Guataporanga', 'SP'),
('Nova Hartz', 'RS'),
('Nova Ibiá', 'BA'),
('Nova Iguaçu', 'RJ'),
('Nova Iorque', 'MA'),
('Nova Ipixuna', 'PA'),
('Nova Itarana', 'BA'),
('Nova Lacerda', 'MT'),
('Nova Lima', 'MG'),
('Nova Londrina', 'PR'),
('Nova Luzitânia', 'MT'),
('Nova Mamoré', 'RO'),
('Nova Módica', 'MG'),
('Nova Monte Verde', 'MT'),
('Nova Mutum', 'MT'),
('Nova Nazaré', 'MT'),
('Nova Odessa', 'SP'),
('Nova Olímpia', 'MT'),
('Nova Olímpia', 'PR'),
('Nova Olinda', 'CE'),
('Nova Olinda', 'PB'),
('Nova Olinda', 'TO'),
('Nova Olinda do Maranhão', 'MA'),
('Nova Olinda do Norte', 'AM'),
('Nova Petrópolis', 'RS'),
('Nova Ponte', 'MG'),
('Nova Porteirinha', 'MG'),
('Nova Prata', 'RS'),
('Nova Prata do Iguaçu', 'PR'),
('Nova Redenção', 'BA'),
('Nova Resende', 'MG'),
('Nova Roma', 'GO'),
('Nova Roma do Sul', 'RS'),
('Nova Rosalândia', 'TO'),
('Nova Russas', 'CE'),
('Nova Santa Bárbara', 'PR'),
('Nova Santa Helena', 'MT'),
('Nova Santa Rita', 'PI'),
('Nova Santa Rita', 'RS'),
('Nova Soure', 'BA'),
('Nova Tebas', 'PR'),
('Nova Trento', 'SC'),
('Nova Ubiratã', 'MT'),
('Nova União', 'MG'),
('Nova União', 'RO'),
('Nova Veneza', 'GO'),
('Nova Veneza', 'SC'),
('Nova Viçosa', 'BA'),
('Nova Xavantina', 'MT'),
('Novais', 'SP'),
('Novo Acordo', 'TO'),
('Novo Airão', 'AM'),
('Novo Alegre', 'TO'),
('Novo Horizonte', 'BA'),
('Novo Horizonte', 'SC'),
('Novo Horizonte', 'SP'),
('Novo Horizonte do Norte', 'MT'),
('Novo Horizonte do Sul', 'MS'),
('Novo Horizonte D''Oeste', 'RO'),
('Novo Jardim', 'TO'),
('Novo Lino', 'AL'),
('Novo Machado', 'RS'),
('Novo Mundo', 'MT'),
('Novo Oriente', 'CE'),
('Novo Oriente de Minas', 'MG'),
('Novo Palmares', 'PR'),
('Novo Paraíso', 'BA'),
('Novo Paraná', 'MT'),
('Novo Planalto', 'GO'),
('Novo Progresso', 'PA'),
('Novo Repartimento', 'PA'),
('Novo Santo Antônio', 'MT'),
('Novo Santo Antônio', 'PI'),
('Novo São Joaquim', 'MT'),
('Novo Tiradentes', 'RS'),
('Novo Triunfo', 'BA'),
('Novo Xingu', 'RS'),
('Novorizontino', 'SP'),
('Nuporanga', 'SP'),
('Óbidos', 'PA'),
('Ocauçu', 'SP'),
('Ocara', 'CE'),
('Oiapoque', 'AP'),
('Olaria', 'MG'),
('Óleo', 'SP'),
('Olho D''Água', 'PB'),
('Olho D''Água', 'PI'),
('Olho D''Água das Cunhãs', 'MA'),
('Olho D''Água das Flores', 'AL'),
('Olho D''Água do Casado', 'AL'),
('Olho D''Água do Piauí', 'PI'),
('Olho D''Água Grande', 'AL'),
('Olindina', 'BA'),
('Olinda', 'PE'),
('Olivença', 'AL'),
('Olivedos', 'PB'),
('Oliveira', 'MG'),
('Oliveira de Fátima', 'TO'),
('Oliveira Fortes', 'MG'),
('Oliveira', 'PE'),
('Olímpia', 'SP'),
('Omate', 'PE'),
('Onda Verde', 'SP'),
('Ondas', 'PR'),
('Oratório', 'AL'),
('Oriximiná', 'PA'),
('Orobó', 'PE'),
('Orocó', 'PE'),
('Orós', 'CE'),
('Ortigueira', 'PR'),
('Ouro Branco', 'AL'),
('Ouro Branco', 'MG'),
('Ouro Branco', 'RN'),
('Ouro Fino', 'MG'),
('Ouro Preto', 'MG'),
('Ouro Preto do Oeste', 'RO'),
('Ouro Verde', 'SP'),
('Ouro Verde de Goiás', 'GO'),
('Ouro Verde de Minas', 'MG'),
('Ouro Verde do Oeste', 'PR'),
('Ouro Velho', 'PB'),
('Ouricuri', 'PE'),
('Ourilândia do Norte', 'PA'),
('Ourinhos', 'SP'),
('Ourizona', 'PR'),
('Ouvidor', 'GO'),
('Pacaembu', 'SP'),
('Pacajá', 'PA'),
('Pacajus', 'CE'),
('Pacatuba', 'CE'),
('Pacatuba', 'SE'),
('Pacaver', 'MG'),
('Paciência', 'PB'),
('Pacoti', 'CE'),
('Pacujá', 'CE'),
('Padre Bernardo', 'GO'),
('Padre Carvalho', 'MG'),
('Padre Marcos', 'PI'),
('Padre Paraíso', 'MG'),
('Paes Landim', 'PI'),
('Pai Pedro', 'MG'),
('Paial', 'SC'),
('Paicandu', 'PR'),
('Paim Filho', 'RS'),
('Paineiras', 'MG'),
('Painel', 'SC'),
('Palestra', 'MG'),
('Paiçandu', 'PR'),
('Palmares', 'PE'),
('Palmares do Sul', 'RS'),
('Palmas', 'TO'),
('Palmas de Monte Alto', 'BA'),
('Palmeira', 'PR'),
('Palmeira', 'SC'),
('Palmeira das Missões', 'RS'),
('Palmeira D''Oeste', 'SP'),
('Palmeira do Piauí', 'PI'),
('Palmeira dos Índios', 'AL'),
('Palmeirais', 'PI'),
('Palmeirândia', 'MA'),
('Palmeirópolis', 'TO'),
('Palmelo', 'GO'),
('Palmital', 'SP'),
('Palmital', 'PR'),
('Palminópolis', 'GO'),
('Palminópolis', 'SP'),
('Palmas', 'PR'),
('Palmares Paulista', 'SP'),
('Palmeiras', 'BA'),
('Palmeiras de Goiás', 'GO'),
('Palmeira do Tocantins', 'TO'),
('Panamá', 'GO'),
('Panelas', 'PE'),
('Panorama', 'SP'),
('Pântano Grande', 'RS'),
('Pão de Açúcar', 'AL'),
('Papanduva', 'SC'),
('Paquetá', 'PI'),
('Pará de Minas', 'MG'),
('Paracambi', 'RJ'),
('Paracatu', 'MG'),
('Paracuru', 'CE'),
('Paragominas', 'PA'),
('Paraguaçu', 'MG'),
('Paraguaçu Paulista', 'SP'),
('Paraí', 'RS'),
('Paraíba do Sul', 'RJ'),
('Paraibano', 'MA'),
('Paraipaba', 'CE'),
('Paraíso', 'SC'),
('Paraíso das Águas', 'MS'),
('Paraíso do Norte', 'PR'),
('Paraíso do Sul', 'RS'),
('Paraíso do Tocantins', 'TO'),
('Paranaiguara', 'GO'),
('Parambu', 'CE'),
('Paramirim', 'BA'),
('Paranacity', 'PR'),
('Paranaguá', 'PR'),
('Paranapoema', 'PR'),
('Paranaíba', 'MS'),
('Paranaíta', 'MT'),
('Paraná', 'RN'),
('Paranapanema', 'SP'),
('Paranavaí', 'PR'),
('Paraty', 'RJ'),
('Paraú', 'RN'),
('Parauapebas', 'PA'),
('Parazinho', 'RN'),
('Pardinho', 'SP'),
('Pareci Novo', 'RS'),
('Parecis', 'RO'),
('Parelhas', 'RN'),
('Pariconha', 'AL'),
('Parintins', 'AM'),
('Paripiranga', 'BA'),
('Paripueira', 'AL'),
('Parobé', 'RS'),
('Passa e Fica', 'RN'),
('Passa Quatro', 'MG'),
('Passa Tempo', 'MG'),
('Passabém', 'MG'),
('Passagem', 'PB'),
('Passagem', 'RN'),
('Passagem Franca', 'MA'),
('Passagem Franca do Piauí', 'PI'),
('Passira', 'PE'),
('Passo de Torres', 'SC'),
('Passo do Sobrado', 'RS'),
('Passo Fundo', 'RS'),
('Passos', 'MG'),
('Passos de Minas', 'MG'),
('Passos do Sobrado', 'RS'),
('Patu', 'RN'),
('Patos', 'PB'),
('Patos de Minas', 'MG'),
('Patrocínio', 'MG'),
('Patrocínio do Muriaé', 'MG'),
('Patrocínio Paulista', 'SP'),
('Pau Brasil', 'BA'),
('Paudalho', 'PE'),
('Pau D''Arco', 'PA'),
('Pau D''Arco', 'TO'),
('Pau dos Ferros', 'RN'),
('Pauini', 'AM'),
('Paulicéia', 'SP'),
('Paulínia', 'SP'),
('Paulino Neves', 'MA'),
('Paulista', 'PB'),
('Paulista', 'PE'),
('Paulinopolis', 'SP'),
('Pavão', 'MG'),
('Pavaçu', 'CE'),
('Pavussu', 'PI'),
('Peabiru', 'PR'),
('Peçanha', 'MG'),
('Pedra Azul', 'MG'),
('Pedra Bela', 'SP'),
('Pedra Branca', 'CE'),
('Pedra Branca do Amapari', 'AP'),
('Pedra do Anta', 'MG'),
('Pedra do Indaiá', 'MG'),
('Pedra Dourada', 'MG'),
('Pedra Grande', 'RN'),
('Pedra Lavrada', 'PB'),
('Pedra Preta', 'MT'),
('Pedralva', 'MG'),
('Pedranópolis', 'SP'),
('Pedrão', 'BA'),
('Pedras Altas', 'RS'),
('Pedras de Fogo', 'PB'),
('Pedras de Maria da Cruz', 'MG'),
('Pedrinhas', 'SE'),
('Pedrinhas Paulista', 'SP'),
('Pedro Afonso', 'TO'),
('Pedro Alexandre', 'BA'),
('Pedro Avelino', 'RN'),
('Pedro Canário', 'ES'),
('Pedro Gomes', 'MS'),
('Pedro Laurentino', 'PI'),
('Pedro Leopoldo', 'MG'),
('Pedro Osório', 'RS'),
('Pedro Régis', 'PB'),
('Pedro Velho', 'RN'),
('Peixe', 'TO'),
('Peixe-Boi', 'PA'),
('Pelotas', 'RS'),
('Penaforte', 'CE'),
('Penalva', 'MA'),
('Penápolis', 'SP'),
('Pendências', 'RN'),
('Penedo', 'AL'),
('Penha', 'SC'),
('Pentecoste', 'CE'),
('Pequeri', 'MG'),
('Pequi', 'MG'),
('Pequizeiro', 'TO'),
('Perdigão', 'MG'),
('Perdizes', 'MG'),
('Perdões', 'MG'),
('Pereira Barreto', 'SP'),
('Pereiras', 'SP'),
('Peres', 'CE'),
('Peri Mirim', 'MA'),
('Periquito', 'MG'),
('Peritiba', 'SC'),
('Perobal', 'PR'),
('Pérola', 'PR'),
('Pérola D''Oeste', 'PR'),
('Peruíbe', 'SP'),
('Pescador', 'MG'),
('Pescaria Brava', 'SC'),
('Pesqueira', 'PE'),
('Piatã', 'BA'),
('Picada Café', 'RS'),
('Picos', 'PI'),
('Piedade', 'SP'),
('Piedade de Caratinga', 'MG'),
('Piedade de Ponte Nova', 'MG'),
('Piedade do Rio Grande', 'MG'),
('Piedade dos Gerais', 'MG'),
('Pilar', 'AL'),
('Pilar', 'PB'),
('Pilar de Goiás', 'GO'),
('Pilar do Sul', 'SP'),
('Pilão Arcado', 'BA'),
('Pilões', 'PB'),
('Pilões', 'RN'),
('Pinhal da Serra', 'RS'),
('Pinhal de São Bento', 'PR'),
('Pinhal Grande', 'RS'),
('Pinhalão', 'PR'),
('Pinhalzinho', 'SP'),
('Pindamonhangaba', 'SP'),
('Pindaré-Mirim', 'MA'),
('Pindoba', 'AL'),
('Pindobaçu', 'BA'),
('Pingo D''Água', 'MG'),
('Pinhais', 'PR'),
('Pinhal', 'RS'),
('Pinhalzinho', 'SC'),
('Pinheiral', 'RJ'),
('Pinheirinho do Vale', 'RS'),
('Pinheiro', 'MA'),
('Pinheiro Machado', 'RS'),
('Pinhão', 'PR'),
('Pinhão', 'SE'),
('Pintadas', 'BA'),
('Pinto Bandeira', 'RS'),
('Pintópolis', 'MG'),
('Pio IX', 'PI'),
('Piquerobi', 'SP'),
('Piquet Carneiro', 'CE'),
('Piquete', 'SP'),
('Piracaia', 'SP'),
('Piracanjuba', 'GO'),
('Piracema', 'MG'),
('Piracicaba', 'SP'),
('Piracuruca', 'PI'),
('Piraí', 'RJ'),
('Piraí do Norte', 'BA'),
('Piraí do Sul', 'PR'),
('Piraju', 'SP'),
('Pirajuba', 'MG'),
('Pirajuí', 'SP'),
('Piranhas', 'AL'),
('Piranhas', 'GO'),
('Pirapemas', 'MA'),
('Pirapetinga', 'MG'),
('Pirapora', 'MG'),
('Pirapora do Bom Jesus', 'SP'),
('Pirapozinho', 'SP'),
('Piraquara', 'PR'),
('Pirassununga', 'SP'),
('Piratininga', 'SP'),
('Piratuba', 'SC'),
('Piraúba', 'MG'),
('Pirenópolis', 'GO'),
('Pires Ferreira', 'CE'),
('Pires do Rio', 'GO'),
('Piripiri', 'PI'),
('Piritiba', 'BA'),
('Pirpirituba', 'PB'),
('Pitanga', 'PR'),
('Pitangueiras', 'PR'),
('Pitangueiras', 'SP'),
('Pitangui', 'MG'),
('Pitimbu', 'PB'),
('Piuí', 'MG'),
('Placas', 'PA'),
('Plácido de Castro', 'AC'),
('Planalto', 'BA'),
('Planalto', 'PR'),
('Planalto', 'RS'),
('Planalto', 'SP'),
('Planalto da Serra', 'MT'),
('Planaltina', 'DF'),
('Planaltina', 'GO'),
('Planaltino', 'BA'),
('Planura', 'MG'),
('Poção', 'PE'),
('Poção de Pedras', 'MA'),
('Pocinhos', 'PB'),
('Poço Branco', 'RN'),
('Poço Dantas', 'PB'),
('Poço das Antas', 'RS'),
('Poço das Trincheiras', 'AL'),
('Poço de José de Moura', 'PB'),
('Poço Redondo', 'SE'),
('Poços de Caldas', 'MG'),
('Poconé', 'MT'),
('Poço Verde', 'SE'),
('Podia', 'MG'),
('Pojuca', 'BA'),
('Poloni', 'SP'),
('Pombal', 'PB'),
('Pompéia', 'SP'),
('Pompéu', 'MG'),
('Pongaí', 'SP'),
('Pontal', 'SP'),
('Pontal do Araguaia', 'MT'),
('Pontal do Paraná', 'PR'),
('Pontes e Lacerda', 'MT'),
('Pontalina', 'GO'),
('Pontianópolis', 'GO'),
('Populina', 'SP'),
('Porangaba', 'SP'),
('Porangatu', 'GO'),
('Porciúncula', 'RJ'),
('Porecatu', 'PR'),
('Portalegre', 'RN'),
('Porteirão', 'GO'),
('Porteirinha', 'MG'),
('Portel', 'PA'),
('Porto', 'PI'),
('Porto Acre', 'AC'),
('Porto Alegre', 'RS'),
('Porto Alegre do Norte', 'MT'),
('Porto Alegre do Tocantins', 'TO'),
('Porto Calvo', 'AL'),
('Porto da Folha', 'SE'),
('Porto de Moz', 'PA'),
('Porto de Pedras', 'AL'),
('Porto do Mangue', 'RN'),
('Porto dos Gaúchos', 'MT'),
('Porto Feliz', 'SP'),
('Porto Ferreira', 'SP'),
('Porto Franco', 'MA'),
('Porto Grande', 'AP'),
('Porto Lucena', 'RS'),
('Porto Mauá', 'RS'),
('Porto Murtinho', 'MS'),
('Porto Nacional', 'TO'),
('Porto Real', 'RJ'),
('Porto Real do Colégio', 'AL'),
('Porto Rico', 'PR'),
('Porto Rico do Maranhão', 'MA'),
('Porto Santana', 'PR'),
('Porto Seguro', 'BA'),
('Porto União', 'SC'),
('Porto Velho', 'RO'),
('Porto Vera Cruz', 'RS'),
('Porto Vitória', 'PR'),
('Porto Walter', 'AC'),
('Porto Xavier', 'RS'),
('Posse', 'GO'),
('Poté', 'MG'),
('Potengi', 'CE'),
('Potim', 'SP'),
('Potirendaba', 'SP'),
('Potiraguá', 'BA'),
('Potiretama', 'CE'),
('Pouso Alegre', 'MG'),
('Pouso Alto', 'MG'),
('Pouso Alegre do Piauí', 'PI'),
('Pouso Redondo', 'SC'),
('Pouso Rico', 'PR'),
('Pracinha', 'SP'),
('Pracuuba', 'AP'),
('Prado', 'BA'),
('Prado Ferreira', 'PR'),
('Pradópolis', 'SP'),
('Prados', 'MG'),
('Praia Grande', 'SP'),
('Praia Grande', 'SC'),
('Pranchita', 'PR'),
('Prata', 'MG'),
('Prata do Piauí', 'PI'),
('Pratânia', 'SP'),
('Pratápolis', 'MG'),
('Presidente Bernardes', 'MG'),
('Presidente Bernardes', 'SP'),
('Presidente Castelo Branco', 'PR'),
('Presidente Castelo Branco', 'SC'),
('Presidente Dutra', 'BA'),
('Presidente Dutra', 'MA'),
('Presidente Epitácio', 'SP'),
('Presidente Figueiredo', 'AM'),
('Presidente Getúlio', 'SC'),
('Presidente Juscelino', 'MG'),
('Presidente Juscelino', 'RN'),
('Presidente Kennedy', 'ES'),
('Presidente Kennedy', 'TO'),
('Presidente Kubitschek', 'MG'),
('Presidente Lucena', 'RS'),
('Presidente Médici', 'RO'),
('Presidente Nereu', 'SC'),
('Presidente Olegário', 'MG'),
('Presidente Prudente', 'SP'),
('Presidente Sarney', 'MA'),
('Presidente Tancredo Neves', 'BA'),
('Presidente Vargas', 'MA'),
('Primavera', 'PA'),
('Primavera', 'PE'),
('Primavera de Rondônia', 'RO'),
('Primavera do Leste', 'MT'),
('Primeiro de Maio', 'PR'),
('Pindorama', 'SP'),
('Princesa', 'SC'),
('Princesa Isabel', 'PB'),
('Professor Jamil', 'GO'),
('Progresso', 'RS'),
('Promissão', 'SP'),
('Propriá', 'SE'),
('Protásio Alves', 'RS'),
('Prudente de Morais', 'MG'),
('Prudentópolis', 'PR'),
('Pugmil', 'TO'),
('Pureza', 'RN'),
('Putinga', 'RS'),
('Quaraí', 'RS'),
('Quadra', 'SP'),
('Quartel Geral', 'MG'),
('Quatá', 'SP'),
('Quatiguá', 'PR'),
('Quatipuru', 'PA'),
('Quatis', 'RJ'),
('Quatro Barras', 'PR'),
('Quatro Pontes', 'PR'),
('Queimada Nova', 'PI'),
('Queimadas', 'BA'),
('Queimadas', 'PB'),
('Queimados', 'RJ'),
('Queluz', 'SP'),
('Queluzito', 'MG'),
('Querência', 'MT'),
('Querência do Norte', 'PR'),
('Quebrangulo', 'AL'),
('Quilombo', 'SC'),
('Quintas do Sol', 'PR'),
('Quinta do Sol', 'PR'),
('Quitandinha', 'PR'),
('Quiterianópolis', 'CE'),
('Quixaba', 'PB'),
('Quixaba', 'PE'),
('Quixadá', 'CE'),
('Quixelô', 'CE'),
('Quixeramobim', 'CE'),
('Quixeré', 'CE'),
('Rafael Fernandes', 'RN'),
('Rafael Godeiro', 'RN'),
('Rafael Jambeiro', 'BA'),
('Rafard', 'SP'),
('Ramilândia', 'PR'),
('Ramirópolis', 'SP'),
('Rancharia', 'SP'),
('Rancho Alegre', 'PR'),
('Rancho Alegre D''Oeste', 'PR'),
('Rancho Queimado', 'SC'),
('Piancó', 'PB'),
('Ribeirão do Largo', 'BA'),
('Ribeirão do Pinhal', 'PR'),
('Ribeirão Preto', 'SP'),
('Ribeirão Vermelho', 'MG'),
('Ribeira do Amparo', 'BA'),
('Ribeira do Piauí', 'PI'),
('Ribeira do Pombal', 'BA'),
('Ribeirãozinho', 'MT'),
('Ribeiro Gonçalves', 'PI'),
('Rifaina', 'SP'),
('Rincão', 'SP'),
('Rio Acima', 'MG'),
('Rio Azul', 'PR'),
('Rio Bananal', 'ES'),
('Rio Bom', 'PR'),
('Rio Bonito', 'RJ'),
('Rio Bonito do Iguaçu', 'PR'),
('Rio Branco', 'AC'),
('Rio Branco', 'MT'),
('Rio Branco do Ivaí', 'PR'),
('Rio Branco do Sul', 'PR'),
('Rio Claro', 'RJ'),
('Rio Claro', 'SP'),
('Rio da Conceição', 'TO'),
('Rio das Antas', 'SC'),
('Rio das Flores', 'RJ'),
('Rio das Ostras', 'RJ'),
('Rio de Contas', 'BA'),
('Rio de Janeiro', 'RJ'),
('Rio do Antônio', 'BA'),
('Rio do Campo', 'SC'),
('Rio do Fogo', 'RN'),
('Rio do Oeste', 'SC'),
('Rio do Prado', 'MG'),
('Rio do Sul', 'SC'),
('Rio Doce', 'MG'),
('Rio dos Bois', 'TO'),
('Rio dos Cedros', 'SC'),
('Rio dos Índios', 'RS'),
('Rio Espera', 'MG'),
('Rio Formoso', 'PE'),
('Rio Fortuna', 'SC'),
('Rio Grande', 'RS'),
('Rio Grande da Serra', 'SP'),
('Rio Manso', 'MG'),
('Rio Maria', 'PA'),
('Rio Negrinho', 'SC'),
('Rio Negro', 'MS'),
('Rio Negro', 'PR'),
('Rio Novo', 'MG'),
('Rio Novo do Sul', 'ES'),
('Rio Paranaíba', 'MG'),
('Rio Pardo', 'RS'),
('Rio Pardo de Minas', 'MG'),
('Rio Piracicaba', 'MG'),
('Rio Pomba', 'MG'),
('Rio Preto', 'MG'),
('Rio Preto da Eva', 'AM'),
('Rio Quente', 'GO'),
('Rio Rufino', 'SC'),
('Rio Sono', 'TO'),
('Rio Tinto', 'PB'),
('Rio Verde', 'GO'),
('Rio Verde de Mato Grosso', 'MS'),
('Rio Vermelho', 'MG'),
('Riolândia', 'SP'),
('Riozinho', 'RS'),
('Riqueza', 'SC'),
('Ritápolis', 'MG'),
('Riversul', 'SP'),
('Rodeio', 'SC'),
('Rodeio Bonito', 'RS'),
('Rodelas', 'BA'),
('Rodolfo Fernandes', 'RN'),
('Rodrigues Alves', 'AC'),
('Rolândia', 'PR'),
('Rolante', 'RS'),
('Rolim de Moura', 'RO'),
('Romaria', 'MG'),
('Romelândia', 'SC'),
('Roncador', 'PR'),
('Ronda Alta', 'RS'),
('Rondinha', 'RS'),
('Rondolândia', 'MT'),
('Rosário', 'MA'),
('Rosário da Limeira', 'MG'),
('Rosário do Catete', 'SE'),
('Rosário do Ivaí', 'PR'),
('Rosário do Sul', 'RS'),
('Roseira', 'SP'),
('Roteiro', 'AL'),
('Rubelita', 'MG'),
('Rubiácea', 'SP'),
('Rubim', 'MG'),
('Rubineia', 'SP'),
('Rurópolis', 'PA'),
('Sabará', 'MG'),
('Sabino', 'SP'),
('Sacramento', 'MG'),
('Safira', 'MG'),
('Sagres', 'SP'),
('Salgadinho', 'PB'),
('Salgadinho', 'PE'),
('Salgado', 'SE'),
('Salgado de São Félix', 'PB'),
('Salinas', 'MG'),
('Salinópolis', 'PA'),
('Salitre', 'CE'),
('Salmourão', 'SP'),
('Saloá', 'PE'),
('Salto', 'SP'),
('Salto do Céu', 'MT'),
('Salto do Itararé', 'PR'),
('Salto do Jacuí', 'RS'),
('Salto do Lontra', 'PR'),
('Salto Grande', 'SP'),
('Salto Veloso', 'SC'),
('Salvador', 'BA'),
('Salvador das Missões', 'RS'),
('Salvador do Sul', 'RS'),
('Santa Adélia', 'SP'),
('Santa Albertina', 'SP'),
('Santa Amélia', 'PR'),
('Santa Bárbara', 'BA'),
('Santa Bárbara', 'MG'),
('Santa Bárbara D''Oeste', 'SP'),
('Santa Bárbara do Monte Verde', 'MG'),
('Santa Bárbara do Pará', 'PA'),
('Santa Bárbara do Sul', 'RS'),
('Santa Bárbara do Tugúrio', 'MG'),
('Santa Brígida', 'BA'),
('Santa Carmem', 'MT'),
('Santa Cecília', 'PB'),
('Santa Cecília', 'SC'),
('Santa Cecília do Pavão', 'PR'),
('Santa Cecília do Sul', 'RS'),
('Santa Clara do Sul', 'RS'),
('Santa Cruz', 'PB'),
('Santa Cruz', 'PE'),
('Santa Cruz', 'RN'),
('Santa Cruz da Baixa Verde', 'PE'),
('Santa Cruz da Conceição', 'SP'),
('Santa Cruz da Esperança', 'SP'),
('Santa Cruz da Vitória', 'BA'),
('Santa Cruz das Palmeiras', 'SP'),
('Santa Cruz de Goiás', 'GO'),
('Santa Cruz de Minas', 'MG'),
('Santa Cruz de Salinas', 'MG'),
('Santa Cruz do Arari', 'PA'),
('Santa Cruz do Capibaribe', 'PE'),
('Santa Cruz do Escalvado', 'MG'),
('Santa Cruz do Piauí', 'PI'),
('Santa Cruz do Rio Pardo', 'SP'),
('Santa Cruz do Sul', 'RS'),
('Santa Cruz dos Milagres', 'PI'),
('Santa Efigênia de Minas', 'MG'),
('Santa Ernestina', 'SP'),
('Santa Fé', 'PR'),
('Santa Fé de Minas', 'MG'),
('Santa Fé do Araguaia', 'TO'),
('Santa Fé do Sul', 'SP'),
('Santa Filomena', 'PE'),
('Santa Filomena', 'PI'),
('Santa Gertrudes', 'SP'),
('Santa Helena', 'MA'),
('Santa Helena', 'PB'),
('Santa Helena', 'PR'),
('Santa Helena', 'SC'),
('Santa Helena de Goiás', 'GO'),
('Santa Inês', 'BA'),
('Santa Inês', 'MA'),
('Santa Inês', 'PB'),
('Santa Inês', 'PR'),
('Santa Isabel', 'GO'),
('Santa Isabel', 'SP'),
('Santa Isabel do Pará', 'PA'),
('Santa Isabel do Rio Negro', 'AM'),
('Santa Izabel do Oeste', 'PR'),
('Santa Juliana', 'MG'),
('Santa Leopoldina', 'ES'),
('Santa Lúcia', 'PR'),
('Santa Lúcia', 'SP'),
('Santa Luzia', 'BA'),
('Santa Luzia', 'MA'),
('Santa Luzia', 'MG'),
('Santa Luzia', 'PB'),
('Santa Luzia D''Oeste', 'RO'),
('Santa Luzia do Norte', 'AL'),
('Santa Luzia do Pará', 'PA'),
('Santa Luzia do Paruá', 'MA'),
('Santa Margarida', 'MG'),
('Santa Margarida do Sul', 'RS'),
('Santa Maria', 'PB'),
('Santa Maria', 'RS'),
('Santa Maria da Boa Vista', 'PE'),
('Santa Maria da Serra', 'SP'),
('Santa Maria da Vitória', 'BA'),
('Santa Maria das Barreiras', 'PA'),
('Santa Maria do Cambucá', 'PE'),
('Santa Maria do Herval', 'RS'),
('Santa Maria do Salto', 'MG'),
('Santa Maria do Suaçuí', 'MG'),
('Santa Maria do Tocantins', 'TO'),
('Santa Maria de Jetibá', 'ES'),
('Santa Mercedes', 'SP'),
('Santa Rita', 'PB'),
('Santa Rita', 'MA'),
('Santa Rita D''Oeste', 'SP'),
('Santa Rita de Caldas', 'MG'),
('Santa Rita de Cássia', 'BA'),
('Santa Rita de Ibitipoca', 'MG'),
('Santa Rita de Jacutinga', 'MG'),
('Santa Rita de Minas', 'MG'),
('Santa Rita de Novo Destino', 'GO'),
('Santa Rita do Araguaia', 'GO'),
('Santa Rita do Itueto', 'MG'),
('Santa Rita do Novo Destino', 'GO'),
('Santa Rita do Passa Quatro', 'SP'),
('Santa Rita do Pardo', 'MS'),
('Santa Rita do Sapucaí', 'MG'),
('Santa Rita do Trivelato', 'MT'),
('Santa Rosa', 'RS'),
('Santa Rosa da Serra', 'MG'),
('Santa Rosa de Goiás', 'GO'),
('Santa Rosa de Lima', 'SC'),
('Santa Rosa de Viterbo', 'SP'),
('Santa Rosa do Sul', 'SC'),
('Santa Rosa do Tocantins', 'TO'),
('Santa Salete', 'SP'),
('Santa Teresa', 'ES'),
('Santa Tereza', 'RS'),
('Santa Tereza de Goiás', 'GO'),
('Santa Tereza do Oeste', 'PR'),
('Santa Tereza do Tocantins', 'TO'),
('Santa Teresinha', 'BA'),
('Santa Teresinha', 'PB'),
('Santa Vitória', 'MG'),
('Santa Vitória do Palmar', 'RS'),
('Santana', 'AP'),
('Santana', 'BA'),
('Santana de Cataguases', 'MG'),
('Santana de Mangueira', 'PB'),
('Santana de Parnaíba', 'SP'),
('Santana do Acaraú', 'CE'),
('Santana do Araguaia', 'PA'),
('Santana do Cariri', 'CE'),
('Santana do Deserto', 'MG'),
('Santana do Garambéu', 'MG'),
('Santana do Ipanema', 'AL'),
('Santana do Jacaré', 'MG'),
('Santana do Mundaú', 'AL'),
('Santana do Paraíso', 'MG'),
('Santana do Piauí', 'PI'),
('Santana do Riacho', 'MG'),
('Santana do São Francisco', 'SE'),
('Santana do Sobrado', 'BA'),
('Santana dos Montes', 'MG'),
('Santana do Livramento', 'RS'),
('Santana do Manhuaçu', 'MG'),
('Santarém', 'PA'),
('Santarém Novo', 'PA'),
('Santiago', 'RS'),
('Santiago do Sul', 'SC'),
('Santo Afonso', 'MT'),
('Santo Amaro', 'BA'),
('Santo Amaro da Imperatriz', 'SC'),
('Santo Anastácio', 'SP'),
('Santo André', 'PB'),
('Santo André', 'SP'),
('Santo Ângelo', 'RS'),
('Santo Antônio', 'RN'),
('Santo Antônio da Alegria', 'SP'),
('Santo Antônio da Barra', 'GO'),
('Santo Antônio da Patrulha', 'RS'),
('Santo Antônio da Platina', 'PR'),
('Santo Antônio das Missões', 'RS'),
('Santo Antônio de Goiás', 'GO'),
('Santo Antônio de Jesus', 'BA'),
('Santo Antônio do Amparo', 'MG'),
('Santo Antônio do Aracanguá', 'SP'),
('Santo Antônio do Aventureiro', 'MG'),
('Santo Antônio do Caiuá', 'PR'),
('Santo Antônio do Descoberto', 'GO'),
('Santo Antônio do Jardim', 'SP'),
('Santo Antônio do Gramame', 'PB'),
('Santo Antônio do Itambé', 'MG'),
('Santo Antônio do Jacinto', 'MG'),
('Santo Antônio do Palma', 'RS'),
('Santo Antônio do Paraíso', 'PR'),
('Santo Antônio do Pinhal', 'SP'),
('Santo Antônio do Retiro', 'MG'),
('Santo Antônio do Rio Abaixo', 'MG'),
('Santo Antônio do Sudoeste', 'PR'),
('Santo Antônio do Tauá', 'PA'),
('Santo Antônio dos Lopes', 'MA'),
('Santo Antônio dos Milagres', 'PI'),
('Santo Estêvão', 'BA'),
('Santo Hipólito', 'MG'),
('Santo Inácio', 'PR'),
('Santo Inácio do Piauí', 'PI'),
('Santo Isidoro', 'MG'),
('Santo Tomás de Aquino', 'MG'),
('Santos', 'SP'),
('Santos Dumont', 'MG'),
('São Benedito', 'CE'),
('São Benedito do Rio Preto', 'MA'),
('São Benedito do Sul', 'PE'),
('São Bento', 'MA'),
('São Bento', 'PB'),
('São Bento Abade', 'MG'),
('São Bento do Norte', 'RN'),
('São Bento do Sul', 'SC'),
('São Bento do Tocantins', 'TO'),
('São Bento do Trairí', 'RN'),
('São Bento do Una', 'PE'),
('São Bernardino', 'SC'),
('São Borja', 'RS'),
('São Caetano de Odivelas', 'PA'),
('São Caetano do Sul', 'SP'),
('São Carlos', 'SP'),
('São Carlos', 'SC'),
('São Carlos do Ivaí', 'PR'),
('São Cristóvão', 'SE'),
('São Desidério', 'BA'),
('São Domingos', 'BA'),
('São Domingos', 'GO'),
('São Domingos', 'PB'),
('São Domingos', 'SC'),
('São Domingos do Araguaia', 'PA'),
('São Domingos do Azeitao', 'MA'),
('São Domingos do Capim', 'PA'),
('São Domingos do Cariri', 'PB'),
('São Domingos do Maranhão', 'MA'),
('São Domingos do Prata', 'MG'),
('São Domingos do Sul', 'RS'),
('São Felipe', 'BA'),
('São Félix', 'BA'),
('São Félix de Balsas', 'MA'),
('São Félix de Minas', 'MG'),
('São Félix do Araguaia', 'MT'),
('São Félix do Coribe', 'BA'),
('São Félix do Piauí', 'PI'),
('São Félix do Xingu', 'PA'),
('São Fernando', 'RN'),
('São Fidélis', 'RJ'),
('São Francisco', 'MG'),
('São Francisco', 'PB'),
('São Francisco', 'SE'),
('São Francisco', 'SP'),
('São Francisco de Assis', 'RS'),
('São Francisco de Assis do Piauí', 'PI'),
('São Francisco de Goiás', 'GO'),
('São Francisco do Brejão', 'MA'),
('São Francisco do Conde', 'BA'),
('São Francisco do Glória', 'MG'),
('São Francisco do Guaporé', 'RO'),
('São Francisco do Maranhão', 'MA'),
('São Francisco do Oeste', 'RN'),
('São Francisco do Pará', 'PA'),
('São Francisco do Piauí', 'PI'),
('São Francisco do Sul', 'SC'),
('São Gabriel', 'BA'),
('São Gabriel', 'RS'),
('São Gabriel da Cachoeira', 'AM'),
('São Gabriel da Palha', 'ES'),
('São Gabriel D''Oeste', 'MS'),
('São Geraldo', 'MG'),
('São Geraldo do Araguaia', 'PA'),
('São Geraldo do Baixio', 'MG'),
('São Gonçalo', 'RJ'),
('São Gonçalo do Abaeté', 'MG'),
('São Gonçalo do Amarante', 'CE'),
('São Gonçalo do Amarante', 'RN'),
('São Gonçalo do Gurguéia', 'PI'),
('São Gonçalo do Pará', 'MG'),
('São Gonçalo do Piauí', 'PI'),
('São Gonçalo do Rio Abaixo', 'MG'),
('São Gonçalo do Rio Preto', 'MG'),
('São Gonçalo do Sapucaí', 'MG'),
('São Gotardo', 'MG'),
('São Jerônimo', 'RS'),
('São João', 'PE'),
('São João', 'PR'),
('São João Batista', 'MA'),
('São João Batista', 'SC'),
('São João Batista do Glória', 'MG'),
('São João da Boa Vista', 'SP'),
('São João da Canabrava', 'PI'),
('São João da Fronteira', 'PI'),
('São João da Lagoa', 'MG'),
('São João da Mata', 'MG'),
('São João da Ponta', 'PA'),
('São João da Ponte', 'MG'),
('São João da Serra', 'PI'),
('São João da Urtiga', 'RS'),
('São João da Vitória', 'MG'),
('São João D''Aliança', 'GO'),
('São João de Iracema', 'SP'),
('São João de Meriti', 'RJ'),
('São João de Monte Claro', 'PR'),
('São João de Pirabas', 'PA'),
('São João do Araguaia', 'PA'),
('São João do Caiuá', 'PR'),
('São João do Cariri', 'PB'),
('São João do Itaperiú', 'SC'),
('São João do Ivaí', 'PR'),
('São João do Manhuaçu', 'MG'),
('São João do Manteninha', 'MG'),
('São João do Miriti', 'RJ'),
('São João do Oeste', 'SC'),
('São João do Oriente', 'MG'),
('São João do Piauí', 'PI'),
('São João do Paraíso', 'MA'),
('São João do Paraíso', 'MG'),
('São João do Patos', 'MA'),
('São João do Sabugi', 'RN'),
('São João do Soter', 'MA'),
('São João do Sul', 'SC'),
('São João do Tigre', 'PB'),
('São João do Triunfo', 'PR'),
('São João Evangelista', 'MG'),
('São João Nepomuceno', 'MG'),
('São Joaquim', 'SC'),
('São Joaquim da Barra', 'SP'),
('São Joaquim de Bicas', 'MG'),
('São Joaquim do Monte', 'PE'),
('São Jorge', 'RS'),
('São Jorge D''Oeste', 'PR'),
('São Jorge do Ivaí', 'PR'),
('São Jorge do Patrocínio', 'PR'),
('São José', 'SC'),
('São José da Barra', 'MG'),
('São José da Coroa Grande', 'PE'),
('São José da Lagoa Tapada', 'PB'),
('São José da Laje', 'AL'),
('São José da Safira', 'MG'),
('São José da Tapera', 'AL'),
('São José da Varginha', 'MG'),
('São José da Vitória', 'BA'),
('São José do Alegre', 'MG'),
('São José do Barreiro', 'SP'),
('São José do Belmonte', 'PE'),
('São José do Bonfim', 'PB'),
('São José do Brejo do Cruz', 'PB'),
('São José do Calçado', 'ES'),
('São José do Campestre', 'RN'),
('São José do Cedro', 'SC'),
('São José do Cerrito', 'SC'),
('São José do Divino', 'MG'),
('São José do Divino', 'PI'),
('São José do Egito', 'PE'),
('São José do Goiabal', 'MG'),
('São José do Herval', 'RS'),
('São José do Inhacorá', 'RS'),
('São José do Jacuípe', 'BA'),
('São José do Jacuri', 'MG'),
('São José do Mipibu', 'RN'),
('São José do Norte', 'RS'),
('São José do Ouro', 'RS'),
('São José do Peixe', 'PI'),
('São José do Piauí', 'PI'),
('São José do Rio Claro', 'MT'),
('São José do Rio Pardo', 'SP'),
('São José do Rio Preto', 'SP'),
('São José do Sabugi', 'PB'),
('São José do Vale do Rio Preto', 'RJ'),
('São José do Sul', 'RS'),
('São José do Tocantins', 'TO'),
('São José do Xingu', 'MT'),
('São José dos Ausentes', 'RS'),
('São José dos Basílios', 'MA'),
('São José dos Campos', 'SP'),
('São José dos Cordeiros', 'PB'),
('São José dos Pinhais', 'PR'),
('São José dos Quatro Marcos', 'MT'),
('São Julião', 'PI'),
('São Leopoldo', 'RS'),
('São Lourenço', 'MG'),
('São Lourenço da Mata', 'PE'),
('São Lourenço do Piauí', 'PI'),
('São Lourenço do Sul', 'RS'),
('São Ludgero', 'SC'),
('São Luís', 'MA'),
('São Luís de Montes Belos', 'GO'),
('São Luís do Curu', 'CE'),
('São Luís do Paraitinga', 'SP'),
('São Luís do Piauí', 'PI'),
('São Luís do Quitunde', 'AL'),
('São Mamede', 'PB'),
('São Manoel do Paraná', 'PR'),
('São Manuel', 'SP'),
('São Marcos', 'RS'),
('São Martinho', 'RS'),
('São Martinho', 'SC'),
('São Martinho da Serra', 'RS'),
('São Martinho D''Oeste', 'RO'),
('São Mateus', 'ES'),
('São Mateus do Maranhão', 'MA'),
('São Mateus do Sul', 'PR'),
('São Miguel', 'RN'),
('São Miguel Arcanjo', 'SP'),
('São Miguel da Boa Vista', 'SC'),
('São Miguel das Matas', 'BA'),
('São Miguel das Missões', 'RS'),
('São Miguel do Aleixo', 'SE'),
('São Miguel do Anta', 'MG'),
('São Miguel do Araguaia', 'GO'),
('São Miguel do Fidalgo', 'PI'),
('São Miguel do Guamá', 'PA'),
('São Miguel do Guaporé', 'RO'),
('São Miguel do Iguaçu', 'PR'),
('São Miguel do Oeste', 'SC'),
('São Miguel do Tapuio', 'PI'),
('São Miguel do Tocantins', 'TO'),
('São Miguel dos Campos', 'AL'),
('São Miguel dos Milagres', 'AL'),
('São Nicolau', 'RS'),
('São Paulo', 'SP'),
('São Paulo das Missões', 'RS'),
('São Paulo de Olivença', 'AM'),
('São Paulo do Potengi', 'RN'),
('São Pedro', 'RN'),
('São Pedro da Água Branca', 'MA'),
('São Pedro da Aldeia', 'RJ'),
('São Pedro da União', 'MG'),
('São Pedro do Butiá', 'RS'),
('São Pedro do Iguaçu', 'PR'),
('São Pedro do Ivaí', 'PR'),
('São Pedro do Paraná', 'PR'),
('São Pedro do Piauí', 'PI'),
('São Pedro do Sul', 'RS'),
('São Pedro do Suaçuí', 'MG'),
('São Pedro dos Ferros', 'MG'),
('São Pedro dos Milagres', 'PI'),
('São Pedro da Cipa', 'MT'),
('São Pedro de Alcântara', 'SC'),
('São Rafael', 'RN'),
('São Raimundo das Mangabeiras', 'MA'),
('São Raimundo do Doca Bezerra', 'MA'),
('São Raimundo Nonato', 'PI'),
('São Romão', 'MG'),
('São Roque', 'SP'),
('São Roque de Minas', 'MG'),
('São Roque do Canaã', 'ES'),
('São Salvador do Tocantins', 'TO'),
('São Sebastião', 'AL'),
('São Sebastião', 'SP'),
('São Sebastião da Amoreira', 'PR'),
('São Sebastião da Boa Vista', 'PA'),
('São Sebastião da Grama', 'SP'),
('São Sebastião da Vargem Alegre', 'MG'),
('São Sebastião do Anta', 'MG'),
('São Sebastião do Caí', 'RS'),
('São Sebastião do Maranhão', 'MG'),
('São Sebastião do Oeste', 'MG'),
('São Sebastião do Paraíso', 'MG'),
('São Sebastião do Passé', 'BA'),
('São Sebastião do Rio Preto', 'MG'),
('São Sebastião do Uatumã', 'AM'),
('São Sepé', 'RS'),
('São Simão', 'GO'),
('São Simão', 'SP'),
('São Tiago', 'MG'),
('São Tomás de Aquino', 'MG'),
('São Tomé', 'PR'),
('São Tomé', 'RN'),
('São Valentim', 'RS'),
('São Valentim do Sul', 'RS'),
('São Valério', 'TO'),
('São Valério do Sul', 'RS'),
('São Vendelino', 'RS'),
('São Vicente', 'RN'),
('São Vicente', 'SP'),
('São Vicente de Minas', 'MG'),
('São Vicente do Sul', 'RS'),
('São Vicente Ferrer', 'MA'),
('São Vicente Ferrer', 'PE'),
('Sapé', 'PB'),
('Sapeaçu', 'BA'),
('Sapé do Norte', 'MG'),
('Sapezal', 'MT'),
('Sarandi', 'PR'),
('Sarandi', 'RS'),
('Sarapuí', 'SP'),
('Sarutaiá', 'SP'),
('Satuba', 'AL'),
('Satubinha', 'MA'),
('Saubara', 'BA'),
('Saúde', 'BA'),
('Schroeder', 'SC'),
('Seabra', 'BA'),
('Seberi', 'RS'),
('Sede Nova', 'RS'),
('Segredo', 'RS'),
('Selbach', 'RS'),
('Selvíria', 'MS'),
('Senador Alexandre Costa', 'MA'),
('Senador Amaral', 'MG'),
('Senador Canedo', 'GO'),
('Senador Cortes', 'MG'),
('Senador Dantas', 'SE'),
('Senador Elói de Souza', 'RN'),
('Senador Firmino', 'MG'),
('Senador Georgino Avelino', 'RN'),
('Senador Guiomard', 'AC'),
('Senador José Bento', 'MG'),
('Senador La Rocque', 'MA'),
('Senador Modestino Gonçalves', 'MG'),
('Senador Pompeu', 'CE'),
('Senador Salgado Filho', 'RS'),
('Senador Sá', 'CE'),
('Sena Madureira', 'AC'),
('Sengés', 'PR'),
('Senhor do Bonfim', 'BA'),
('Senhora de Oliveira', 'MG'),
('Senhora do Carmo', 'MG'),
('Senhora do Porto', 'MG'),
('Senhora dos Remédios', 'MG'),
('Sentinela do Sul', 'RS'),
('Serra', 'ES'),
('Serra Azul', 'SP'),
('Serra Azul de Minas', 'MG'),
('Serra Branca', 'PB'),
('Serra Caiada', 'RN'),
('Serra do Mel', 'RN'),
('Serra da Saudade', 'MG'),
('Serra da Raiz', 'PB'),
('Serra do Ramalho', 'BA'),
('Serra do Salitre', 'MG'),
('Serra dos Aimorés', 'MG'),
('Serra Grande', 'PB'),
('Serra Negra', 'SP'),
('Serra Negra do Norte', 'RN'),
('Serra Nova Dourada', 'MT'),
('Serra Preta', 'BA'),
('Serra Talhada', 'PE'),
('Serrana', 'SP'),
('Serrania', 'MG'),
('Serrano do Maranhão', 'MA'),
('Serranópolis', 'GO'),
('Serranópolis de Minas', 'MG'),
('Serranópolis do Iguaçu', 'PR'),
('Serraria', 'PB'),
('Serrinha', 'BA'),
('Serrinha', 'RN'),
('Sertaneja', 'PR'),
('Sertânia', 'PE'),
('Sertanópolis', 'PR'),
('Sertão', 'RS'),
('Sertão Santana', 'RS'),
('Sertãozinho', 'PB'),
('Sertãozinho', 'SP'),
('Sete Barras', 'SP'),
('Sete de Setembro', 'RS'),
('Sete Lagoas', 'MG'),
('Sete Quedas', 'MS'),
('Setubinha', 'MG'),
('Severiano Melo', 'RN'),
('Severiano de Almeida', 'RS'),
('Severínia', 'SP'),
('Sibéria', 'SP'),
('Sidrolândia', 'MS'),
('Sigefredo Pacheco', 'PI'),
('Silva Jardim', 'RJ'),
('Silvânia', 'GO'),
('Silvanópolis', 'TO'),
('Silveira Martins', 'RS'),
('Silveirânia', 'MG'),
('Silves', 'AM'),
('Silves', 'SP'),
('Simões', 'PI'),
('Simões Filho', 'BA'),
('Simolândia', 'GO'),
('Simonésia', 'MG'),
('Simons', 'MG'),
('Simplício Mendes', 'PI'),
('Sinimbu', 'RS'),
('Sinop', 'MT'),
('Siqueira Campos', 'PR'),
('Sirinhaém', 'PE'),
('Siriri', 'SE'),
('Sítio D''Abadia', 'GO'),
('Sítio do Mato', 'BA'),
('Sítio do Quinto', 'BA'),
('Sítio Novo', 'MA'),
('Sítio Novo', 'RN'),
('Sítio Novo do Tocantins', 'TO'),
('Sobradinho', 'BA'),
('Sobradinho', 'RS'),
('Sobral', 'CE'),
('Socorro', 'SP'),
('Socorro do Piauí', 'PI'),
('Solânea', 'PB'),
('Soledade', 'PB'),
('Soledade', 'RS'),
('Soledade de Minas', 'MG'),
('Solonópole', 'CE'),
('Sombrio', 'SC'),
('Sonora', 'MS'),
('Sorocaba', 'SP'),
('Sorriso', 'MT'),
('Sossêgo', 'PB'),
('Sousa', 'PB'),
('Stand', 'CE'),
('Subaúma', 'BA'),
('Sumaré', 'SP'),
('Sumé', 'PB'),
('Tabaporã', 'MT'),
('Tabocão', 'TO'),
('Taboleiro Grande', 'RN'),
('Tabuleiro', 'MG'),
('Tabira', 'PE'),
('Taboão da Serra', 'SP'),
('Tacaimbó', 'PE'),
('Tacaratu', 'PE'),
('Taciba', 'SP'),
('Taguatinga', 'DF'),
('Taguatinga', 'TO'),
('Taiaçu', 'SP'),
('Tailândia', 'PA'),
('Taió', 'SC'),
('Taiuva', 'SP'),
('Talismã', 'TO'),
('Tamandaré', 'PE'),
('Tamarana', 'PR'),
('Tambau', 'SP'),
('Tamboril', 'CE'),
('Tamboril do Piauí', 'PI'),
('Tanabi', 'SP'),
('Tangará', 'RN'),
('Tangará', 'SC'),
('Tangará da Serra', 'MT'),
('Tanguá', 'RJ'),
('Tanhaçu', 'BA'),
('Tanque D''Arca', 'AL'),
('Tanque do Piauí', 'PI'),
('Tanquinho', 'BA'),
('Taperoá', 'BA'),
('Taperoá', 'PB'),
('Tapira', 'MG'),
('Tapira', 'PR'),
('Tapiraí', 'MG'),
('Tapiraí', 'SP'),
('Tapiramutá', 'BA'),
('Tapiratiba', 'SP'),
('Tapurah', 'MT'),
('Taquara', 'RS'),
('Taquaraçu de Minas', 'MG'),
('Taquaral de Goiás', 'GO'),
('Taquaritinga', 'SP'),
('Taquaritinga do Norte', 'PE'),
('Taquarituba', 'SP'),
('Taquaruçu do Sul', 'RS'),
('Taquarana', 'AL'),
('Taquari', 'RS'),
('Taquarivaí', 'SP'),
('Tarabai', 'SP'),
('Tarauacá', 'AC'),
('Tarrafas', 'CE'),
('Tartarugalzinho', 'AP'),
('Tarumã', 'SP'),
('Tarumirim', 'MG'),
('Tapes', 'RS'),
('Tatuí', 'SP'),
('Tauá', 'CE'),
('Taubaté', 'SP'),
('Tefé', 'AM'),
('Teixeira', 'PB'),
('Teixeira de Freitas', 'BA'),
('Teixeira Soares', 'PR'),
('Teixeiras', 'MG'),
('Teixeirópolis', 'RO'),
('Tejuçuoca', 'CE'),
('Tejupá', 'SP'),
('Telha', 'SE'),
('Telêmaco Borba', 'PR'),
('Tenente Ananias', 'RN'),
('Tenente Laurentino Cruz', 'RN'),
('Tenório', 'PB'),
('Teodoro Sampaio', 'BA'),
('Teodoro Sampaio', 'SP'),
('Teofilândia', 'BA'),
('Teófilo Otoni', 'MG'),
('Teolândia', 'BA'),
('Teotônio Vilela', 'AL'),
('Terra Boa', 'PR'),
('Terra de Areia', 'RS'),
('Terra Nova', 'BA'),
('Terra Nova', 'PE'),
('Terra Nova', 'MS'),
('Terra Nova do Norte', 'MT'),
('Terra Rica', 'PR'),
('Terra Roxa', 'PR'),
('Terra Roxa', 'SP'),
('Tesouro', 'MT'),
('Teutônia', 'RS'),
('Tijuca', 'RJ'),
('Tigrinhos', 'SC'),
('Tijucas', 'SC'),
('Tijucas do Sul', 'PR'),
('Timbaúba', 'PE'),
('Timbaúba dos Batistas', 'RN'),
('Timbe do Sul', 'SC'),
('Timbiras', 'MA'),
('Timbó', 'SC'),
('Timbó Grande', 'SC'),
('Timburi', 'SP'),
('Timon', 'MA'),
('Timóteo', 'MG'),
('Tio Hugo', 'RS'),
('Tiradentes', 'MG'),
('Tiradentes do Sul', 'RS'),
('Tobias Barreto', 'SE'),
('Tocantínia', 'TO'),
('Tocantinópolis', 'TO'),
('Tocantins', 'MG'),
('Tocoió', 'PE'),
('Tocos do Moji', 'MG'),
('Toledo', 'MG'),
('Toledo', 'PR'),
('Tomar do Geru', 'SE'),
('Tomazina', 'PR'),
('Tombos', 'MG'),
('Tomé-Açu', 'PA'),
('Tonantins', 'AM'),
('Toritama', 'PE'),
('Torixoréu', 'MT'),
('Torre de Pedra', 'SP'),
('Torres', 'RS'),
('Torrinha', 'SP'),
('Touros', 'RN'),
('Trabiju', 'SP'),
('Tracunhaém', 'PE'),
('Traipu', 'AL'),
('Trairi', 'CE'),
('Trajano de Moraes', 'RJ'),
('Tramandaí', 'RS'),
('Travesseiro', 'RS'),
('Tremedal', 'BA'),
('Tremembé', 'SP'),
('Três Arroios', 'RS'),
('Três Barras', 'SC'),
('Três Barras do Paraná', 'PR'),
('Três Cachoeiras', 'RS'),
('Três Coroas', 'RS'),
('Três Corações', 'MG'),
('Três de Maio', 'RS'),
('Três Forquilhas', 'RS'),
('Três Fronteiras', 'SP'),
('Três Iriãs', 'RS'),
('Três Lagoas', 'MS'),
('Três Marias', 'MG'),
('Três Palmeiras', 'RS'),
('Três Passos', 'RS'),
('Três Pontas', 'MG'),
('Três Ranchos', 'GO'),
('Três Rios', 'RJ'),
('Treviso', 'SC'),
('Treze de Maio', 'SC'),
('Treze Tílias', 'SC'),
('Trombudo Central', 'SC'),
('Tubarão', 'SC'),
('Tucano', 'BA'),
('Tucumã', 'PA'),
('Tucunduva', 'RS'),
('Tupaciguara', 'MG'),
('Tupanasi', 'PR'),
('Tupandi', 'RS'),
('Tupã', 'SP'),
('Tupanci', 'RS'),
('Tuparendi', 'RS'),
('Tuparetama', 'PE'),
('Tupi Paulista', 'SP'),
('Tupirama', 'TO'),
('Tupiratins', 'TO'),
('Turiaçu', 'MA'),
('Turilândia', 'MA'),
('Turiúba', 'SP'),
('Turmalina', 'MG'),
('Turmalina', 'SP'),
('Turuçu', 'RS'),
('Turvânia', 'GO'),
('Turvelândia', 'GO'),
('Turvo', 'PR'),
('Turvo', 'SC'),
('Tutóia', 'MA'),
('Uauá', 'BA'),
('Ubá', 'MG'),
('Ubaí', 'MG'),
('Ubaíra', 'BA'),
('Ubaitaba', 'BA'),
('Ubarana', 'SP'),
('Ubatã', 'BA'),
('Ubatuba', 'SP'),
('Uberaba', 'MG'),
('Uberlândia', 'MG'),
('Ubirajara', 'SP'),
('Ubiratã', 'PR'),
('Uirapuru', 'GO'),
('Umuarama', 'PR'),
('Una', 'BA'),
('Unaí', 'MG'),
('União', 'PI'),
('União da Serra', 'RS'),
('União da Vitória', 'PR'),
('União de Minas', 'MG'),
('União do Oeste', 'SC'),
('União do Sul', 'MT'),
('União dos Palmares', 'AL'),
('Uniflor', 'PR'),
('Uraí', 'PR'),
('Urandi', 'BA'),
('Urânia', 'SP'),
('Uruaçu', 'GO'),
('Uruana', 'GO'),
('Uruana de Minas', 'MG'),
('Uruará', 'PA'),
('Urubici', 'SC'),
('Uruburetama', 'CE'),
('Urucânia', 'MG'),
('Urucará', 'AM'),
('Uruçuca', 'BA'),
('Uruçuí', 'PI'),
('Urucurituba', 'AM'),
('Uruguaiana', 'RS'),
('Uruoca', 'CE'),
('Urupá', 'RO'),
('Urupema', 'SC'),
('Urussanga', 'SC'),
('Urubaretama', 'CE'),
('Urupês', 'SP'),
('Utinga', 'BA'),
('Vacaria', 'RS'),
('Vale do Anari', 'RO'),
('Vale do Paraíso', 'RO'),
('Vale Real', 'RS'),
('Vale Verde', 'RS'),
('Valença', 'BA'),
('Valença', 'RJ'),
('Valença do Piauí', 'PI'),
('Valente', 'BA'),
('Valinhos', 'SP'),
('Valparaíso', 'SP'),
('Valparaíso de Goiás', 'GO'),
('Vanini', 'RS'),
('Vargeão', 'SC'),
('Vargem', 'SC'),
('Vargem Bonita', 'MG'),
('Vargem Bonita', 'SC'),
('Vargem Grande', 'MA'),
('Vargem Grande do Sul', 'SP'),
('Vargem Grande Paulista', 'SP'),
('Vargem Alegre', 'MG'),
('Varjota', 'CE'),
('Varjão', 'GO'),
('Varjão de Minas', 'MG'),
('Várzea', 'PB'),
('Várzea', 'RN'),
('Várzea Alegre', 'CE'),
('Várzea da Palma', 'MG'),
('Várzea da Roça', 'BA'),
('Várzea do Poço', 'BA'),
('Várzea Grande', 'MT'),
('Várzea Grande', 'PI'),
('Várzea Nova', 'BA'),
('Varzedo', 'BA'),
('Vazante', 'MG'),
('Venâncio Aires', 'RS'),
('Venturosa', 'PE'),
('Vera', 'MT'),
('Vera Cruz', 'BA'),
('Vera Cruz', 'RN'),
('Vera Cruz', 'SP'),
('Vera Cruz do Oeste', 'PR'),
('Vera Mendes', 'PI'),
('Veranópolis', 'RS'),
('Verdelândia', 'MG'),
('Verê', 'PR'),
('Vereda', 'BA'),
('Veríssimo', 'MG'),
('Vertente do Lério', 'PE'),
('Vertentes', 'PE'),
('Vespasiano', 'MG'),
('Vespasiano Correa', 'RS'),
('Viadutos', 'RS'),
('Viamão', 'RS'),
('Viana', 'ES'),
('Viana', 'MA'),
('Vianópolis', 'GO'),
('Vicência', 'PE'),
('Vicente Dutra', 'RS'),
('Vicentinópolis', 'GO'),
('Vicentinópolis', 'MS'),
('Viçosa', 'AL'),
('Viçosa', 'MG'),
('Viçosa do Ceará', 'CE'),
('Victor Graeff', 'RS'),
('Videira', 'SC'),
('Vieiras', 'MG'),
('Vieirópolis', 'PB'),
('Vigía', 'PA'),
('Vila Boa', 'GO'),
('Vila Flores', 'RS'),
('Vila Nova do Piauí', 'PI'),
('Vila Nova dos Martírios', 'MA'),
('Vila Pavão', 'ES'),
('Vila Propício', 'GO'),
('Vila Rica', 'MT'),
('Vilhena', 'RO'),
('Vinhedo', 'SP'),
('Viradouro', 'SP'),
('Virgem da Lapa', 'MG'),
('Virgínia', 'MG'),
('Virginópolis', 'MG'),
('Virgolândia', 'MG'),
('Virgínia', 'SP'),
('Visconde do Rio Branco', 'MG'),
('Vista Alegre', 'RS'),
('Vista Alegre do Prata', 'RS'),
('Vista Gaúcha', 'RS'),
('Vista Serrana', 'PB'),
('Vitória', 'ES'),
('Vitória Brasil', 'SP'),
('Vitória da Conquista', 'BA'),
('Vitória das Missões', 'RS'),
('Vitória de Santo Antão', 'PE'),
('Vitória do Jari', 'AP'),
('Vitória do Mearim', 'MA'),
('Vitória do Xingu', 'PA'),
('Vitorino', 'PR'),
('Vitorino Freire', 'MA'),
('Volta Grande', 'MG'),
('Volta Redonda', 'RJ'),
('Votuporanga', 'SP'),
('Wagner', 'BA'),
('Wanderley', 'BA'),
('Wenceslau Braz', 'MG'),
('Wenceslau Braz', 'PR'),
('Wenceslau Guimarães', 'BA'),
('Westfália', 'RS'),
('Xambioá', 'TO'),
('Xambrê', 'PR'),
('Xangri-Lá', 'RS'),
('Xanxerê', 'SC'),
('Xapuri', 'AC'),
('Xavantina', 'SC'),
('Xaxim', 'SC'),
('Xique-Xique', 'BA'),
('Zacarias', 'SP'),
('Zabelê', 'PB'),
('Zortéa', 'SC');